<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'; import { assetApi } from '../api/assets'; import { rememberOperator, savedOperator } from '../api/inventory'; import { objectApi } from '../api/objects'; import type { Asset, InfrastructureObject, InventoryLocation, Organization } from '../types'
type AssetAction = 'stock' | 'deploy' | 'transfer' | 'complete-transfer' | 'retire' | 'recover'
const props = defineProps<{ asset: Asset; action: AssetAction }>(); const emit = defineEmits<{ close: []; completed: [] }>()
const locations = ref<InventoryLocation[]>([]), racks = ref<InfrastructureObject[]>([]), organizations = ref<Organization[]>([]); const targetId = ref(''), notes = ref(''), reason = ref(''), disposition = ref<'RMA' | 'SCRAPPED' | 'RETURNED_TO_VENDOR'>('SCRAPPED'), operatorId = ref(savedOperator()), submitting = ref(false), creating = ref(false)
const locationForm = ref({ name: '', warehouse: '', shelf: '', location_code: '', description: '' })
const titles: Record<AssetAction, string> = { stock: '资产入库', deploy: '部署资产', transfer: '资产调拨', 'complete-transfer': '完成入库', retire: '资产退役', recover: '退役撤销' }
const canSubmit = computed(() => { if (props.action === 'retire' || props.action === 'recover') return Boolean(reason.value.trim()); if (props.action === 'stock' || props.action === 'deploy') return Boolean(targetId.value && operatorId.value); return Boolean(targetId.value) })
async function createLocation() { if (!locationForm.value.name || !locationForm.value.warehouse || !locationForm.value.location_code) return; const { data } = await assetApi.createLocation({ ...locationForm.value, shelf: locationForm.value.shelf || null, description: locationForm.value.description || null }); locations.value = (await assetApi.locations()).data.items; targetId.value = data.id; creating.value = false }
async function submit() { if (!canSubmit.value) return; submitting.value = true; try { rememberOperator(operatorId.value); if (props.action === 'stock') await assetApi.stock(props.asset.id, targetId.value, operatorId.value, props.asset.version); else if (props.action === 'deploy') await assetApi.deploy(props.asset.id, targetId.value, operatorId.value, props.asset.version); else if (props.action === 'transfer') await assetApi.transfer(props.asset.id, targetId.value, notes.value.trim(), props.asset.version); else if (props.action === 'complete-transfer') await assetApi.completeTransfer(props.asset.id, targetId.value, props.asset.version); else if (props.action === 'retire') await assetApi.retire(props.asset.id, reason.value.trim(), disposition.value, props.asset.version); else await assetApi.recover(props.asset.id, reason.value.trim(), props.asset.version); emit('completed') } finally { submitting.value = false } }
onMounted(async () => { if (props.action === 'deploy') racks.value = (await objectApi.racks()).data.items; else if (props.action === 'stock' || props.action === 'complete-transfer') locations.value = (await assetApi.locations()).data.items; else if (props.action === 'transfer') { const { adminApi } = await import('../api/admin'); organizations.value = (await adminApi.organizations({ page: 1, page_size: 200 })).data.items } })
</script>
<template><a-modal :visible="true" :title="titles[action]" :ok-loading="submitting" :ok-button-props="{ disabled: !canSubmit }" ok-text="确认" cancel-text="取消" :mask-closable="false" @cancel="emit('close')" @ok="submit">
  <p class="modal-eyebrow">资产 {{ asset.asset_number }}</p><a-form :model="{}" layout="vertical">
    <template v-if="action === 'stock' || action === 'complete-transfer'"><a-form-item label="库存位置" required><a-select v-model="targetId" placeholder="请选择库存位置"><a-option v-for="item in locations" :key="item.id" :value="item.id">{{ item.name }}（{{ item.warehouse }}/{{ item.shelf || item.location_code }}）</a-option></a-select></a-form-item><a-alert v-if="!locations.length" type="warning">暂无库存位置，请先新建位置。</a-alert><a-button v-if="action === 'stock'" type="text" @click="creating = !creating">{{ creating ? '收起新建表单' : '+ 新建库存位置' }}</a-button><a-card v-if="action === 'stock' && creating" class="inline-location-card" :bordered="false"><div class="modal-form-grid"><a-form-item label="位置名称"><a-input v-model="locationForm.name" /></a-form-item><a-form-item label="仓库"><a-input v-model="locationForm.warehouse" /></a-form-item><a-form-item label="货架"><a-input v-model="locationForm.shelf" /></a-form-item><a-form-item label="位置编码"><a-input v-model="locationForm.location_code" /></a-form-item></div><a-button :disabled="!locationForm.name || !locationForm.warehouse || !locationForm.location_code" @click="createLocation">创建并选择</a-button></a-card></template>
    <a-form-item v-else-if="action === 'deploy'" label="目标机柜" required><a-select v-model="targetId" placeholder="请选择 Rack"><a-option v-for="rack in racks" :key="rack.id" :value="rack.id">{{ rack.name }}{{ rack.model ? ` · ${rack.model}` : '' }}</a-option></a-select></a-form-item>
    <template v-else-if="action === 'transfer'"><a-form-item label="目标组织" required><a-select v-model="targetId" placeholder="请选择目标组织"><a-option v-for="org in organizations.filter(item => item.is_active)" :key="org.id" :value="org.id">{{ org.name }}</a-option></a-select></a-form-item><a-form-item label="备注"><a-textarea v-model="notes" :auto-size="{ minRows: 3, maxRows: 5 }" placeholder="请输入调拨备注（选填）" /></a-form-item></template>
    <template v-else-if="action === 'retire'"><a-alert type="warning">确认后，关联基础设施对象将标记为退役。</a-alert><a-form-item label="退役原因" required><a-textarea v-model="reason" :auto-size="{ minRows: 3, maxRows: 5 }" /></a-form-item><a-form-item label="处置方式"><a-select v-model="disposition"><a-option value="RMA">RMA（返厂维修）</a-option><a-option value="SCRAPPED">报废</a-option><a-option value="RETURNED_TO_VENDOR">退还供应商</a-option></a-select></a-form-item></template>
    <template v-else-if="action === 'recover'"><a-alert type="warning">撤销退役后，资产与关联对象将恢复为维护中。</a-alert><a-form-item label="撤销原因" required><a-textarea v-model="reason" :auto-size="{ minRows: 3, maxRows: 5 }" /></a-form-item></template>
    <a-form-item v-if="action === 'stock' || action === 'deploy'" label="操作用户 ID" required><a-input v-model="operatorId" placeholder="后端要求的用户 UUID" /></a-form-item>
  </a-form>
</a-modal></template>
