<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'; import { useRoute, useRouter } from 'vue-router'; import { IconLeft } from '@arco-design/web-vue/es/icon'; import { assetApi } from '../api/assets'; import { objectApi } from '../api/objects'; import AssetActionModal from '../components/AssetActionModal.vue'; import { loadCatalogs, useCatalog } from '../stores/catalog'; import type { AssetDetail, LifecycleEvent, ObjectType } from '../types'
type AssetAction = 'stock' | 'deploy' | 'transfer' | 'complete-transfer' | 'retire' | 'recover'
const route = useRoute(), router = useRouter(); const asset = ref<AssetDetail | null>(null), events = ref<LifecycleEvent[]>([]), types = ref<ObjectType[]>([]), action = ref<AssetAction | null>(null), loading = ref(true); const { organizationMap, locationMap } = useCatalog()
const typeName = computed(() => types.value.find((item) => item.id === asset.value?.object.object_type_id)?.display_name || types.value.find((item) => item.id === asset.value?.object.object_type_id)?.name || '—')
const labels: Record<string, string> = { REQUESTED: '提交采购申请', APPROVED: '采购申请批准', ORDERED: '采购下单', PURCHASED: '完成采购', RECEIVED: '到货验收', STOCK: '资产入库', IN_TRANSIT: '运输中', DEPLOYING: '开始部署', DEPLOYED: '完成部署', ACTIVE: '投入使用', MAINTENANCE: '进入维护', TRANSFERRED: '资产调拨', RETIRED: '资产退役', RECOVERED: '退役撤销', REJECTED: '申请驳回' }
const statusName: Record<string, string> = { RECEIVED: '已到货', STOCK: '库存中', ACTIVE: '使用中', DEPLOYED: '已部署', MAINTENANCE: '维护中', TRANSFERRED: '调拨中', RETIRED: '已退役', RECOVERED: '已撤销' }
const statusColor = (value: string) => ({ RECEIVED: 'orange', STOCK: 'green', ACTIVE: 'green', DEPLOYED: 'lime', MAINTENANCE: 'orangered', TRANSFERRED: 'purple', RETIRED: 'gray', RECOVERED: 'blue' }[value] || 'gray')
function date(value: string | null | undefined) { return value ? new Date(value).toLocaleString('zh-CN') : '—' }
async function load() { loading.value = true; try { const id = String(route.params.id); const [detail, lifecycle, objectTypes] = await Promise.all([assetApi.get(id), assetApi.lifecycle(id), objectApi.types(), loadCatalogs()]); asset.value = detail.data; events.value = lifecycle.data.items; types.value = objectTypes.data.items } finally { loading.value = false } }
async function completed() { action.value = null; await load() } onMounted(load)
</script>
<template><section class="page arco-page"><a-button type="text" class="detail-back" @click="router.push('/assets')"><template #icon><IconLeft /></template>返回资产台账</a-button><a-spin :loading="loading" class="detail-spin"><template v-if="asset">
  <header class="page-header"><div><p class="eyebrow">{{ asset.asset_number }}</p><h1>{{ asset.object.name }} <a-tag :color="statusColor(asset.lifecycle_status)" bordered>{{ statusName[asset.lifecycle_status] || asset.lifecycle_status }}</a-tag></h1><p class="muted">{{ typeName }} · {{ asset.object.model || '型号未记录' }}</p></div><a-space wrap><a-button v-if="asset.lifecycle_status === 'RECEIVED'" type="primary" @click="action = 'stock'">办理入库</a-button><a-button v-if="asset.lifecycle_status === 'STOCK'" type="primary" @click="action = 'deploy'">部署到机柜</a-button><a-button v-if="['ACTIVE', 'STOCK'].includes(asset.lifecycle_status)" @click="action = 'transfer'">调拨</a-button><a-button v-if="asset.lifecycle_status === 'TRANSFERRED'" type="primary" @click="action = 'complete-transfer'">完成入库</a-button><a-button v-if="['ACTIVE', 'STOCK', 'MAINTENANCE'].includes(asset.lifecycle_status)" status="danger" @click="action = 'retire'">退役</a-button><a-button v-if="asset.lifecycle_status === 'RETIRED'" @click="action = 'recover'">退役撤销</a-button></a-space></header>
  <div class="arco-detail-grid"><a-card title="基本信息" :bordered="false"><a-descriptions :column="1" bordered size="large"><a-descriptions-item label="资产编号">{{ asset.asset_number }}</a-descriptions-item><a-descriptions-item label="供应商">{{ asset.vendor || '—' }}</a-descriptions-item><a-descriptions-item label="到货日期">{{ asset.received_date || '—' }}</a-descriptions-item><a-descriptions-item label="采购成本">{{ asset.cost == null ? '—' : `${asset.currency || 'CNY'} ${asset.cost}` }}</a-descriptions-item><a-descriptions-item label="所有者组织">{{ organizationMap[asset.owner_org_id || ''] || '—' }}</a-descriptions-item><a-descriptions-item label="库存位置">{{ asset.inventory_location?.name || locationMap[asset.inventory_location_id || ''] || '—' }}</a-descriptions-item></a-descriptions></a-card>
    <a-card title="关联对象摘要" :bordered="false"><template #extra><a-link @click="router.push(`/objects/${asset.object_id}`)">查看对象</a-link></template><a-descriptions :column="1" bordered size="large"><a-descriptions-item label="对象名称">{{ asset.object.name }}</a-descriptions-item><a-descriptions-item label="对象类型">{{ typeName }}</a-descriptions-item><a-descriptions-item label="序列号">{{ asset.object.serial_number || '—' }}</a-descriptions-item><a-descriptions-item label="型号">{{ asset.object.model || '—' }}</a-descriptions-item><a-descriptions-item label="对象状态">{{ asset.object.status }}</a-descriptions-item><a-descriptions-item label="部署位置">{{ locationMap[asset.object.deployed_location_id || ''] || '—' }}</a-descriptions-item></a-descriptions></a-card></div>
  <a-card class="arco-lifecycle-card" title="生命周期" :bordered="false"><template #extra><span class="muted">共 {{ events.length }} 个事件</span></template><a-empty v-if="!events.length" description="暂无生命周期事件" /><a-timeline v-else><a-timeline-item v-for="(event, index) in events" :key="`${event.event_type}-${index}`" :label="date(event.occurred_at)"><strong>{{ labels[event.event_type] || event.event_type }}</strong><a-collapse v-if="Object.keys(event.details || {}).length" :bordered="false"><a-collapse-item header="事件详情" :key="String(index)"><pre class="event-json">{{ JSON.stringify(event.details, null, 2) }}</pre></a-collapse-item></a-collapse></a-timeline-item></a-timeline></a-card>
  <AssetActionModal v-if="action" :asset="asset" :action="action" @close="action = null" @completed="completed" />
</template></a-spin></section></template>
