<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { dashboardApi } from '../api/dashboard'
import type { DashboardAssets, DashboardOverview, OperationsSummary } from '../types'
const overview=ref<DashboardOverview|null>(null), assets=ref<DashboardAssets|null>(null), operations=ref<OperationsSummary|null>(null), loading=ref(true)
const maxDevice=computed(()=>Math.max(1,...(overview.value?.devices.by_type.map(item=>item.count)||[1])))
const maxAsset=computed(()=>Math.max(1,...(assets.value?.by_status.map(item=>item.count)||[1])))
const statusName:Record<string,string>={REQUESTED:'已申请',APPROVED:'已批准',ORDERED:'已下单',PURCHASED:'已采购',RECEIVED:'已接收',STOCK:'库存中',IN_TRANSIT:'运输中',DEPLOYING:'部署中',DEPLOYED:'已部署',ACTIVE:'使用中',MAINTENANCE:'维护中',TRANSFERRED:'已调拨',RETIRED:'已退役',RECOVERED:'已回收',CREATED:'已创建',ASSIGNED:'已分配',PROCESSING:'处理中',WAITING:'等待中',SUSPENDED:'已暂停',RESOLVED:'已解决',CLOSED:'已关闭',CANCELLED:'已取消',REOPENED:'已重开'}
onMounted(async()=>{try{const [o,a,p]=await Promise.all([dashboardApi.overview(),dashboardApi.assets(),dashboardApi.operations()]);overview.value=o.data;assets.value=a.data;operations.value=p.data}finally{loading.value=false}})
</script>
<template><section class="page"><header class="page-header"><div><p class="eyebrow">OPERATIONS OVERVIEW</p><h1>Dashboard</h1><p class="muted">基础设施资产与运维运营总览</p></div></header>
<div v-if="loading" class="card empty">正在加载运营数据…</div><template v-else>
<div class="metric-grid"><div class="card metric-card"><span>设备总数</span><strong>{{overview?.devices.total||0}}</strong><small>基础设施对象</small></div><div class="card metric-card"><span>资产总数</span><strong>{{assets?.total||0}}</strong><small>资产记录</small></div><div class="card metric-card"><span>待处理工单</span><strong>{{operations?.open||0}}</strong><small>共 {{operations?.total||0}} 张</small></div><div class="card metric-card"><span>本月新增工单</span><strong>{{operations?.new_this_month||0}}</strong><small>已解决 {{operations?.resolved||0}} 张</small></div><div class="card metric-card"><span>平均修复时间</span><strong>{{operations?.average_repair_hours||0}}<em> 小时</em></strong><small>已解决工单平均值</small></div></div>
<div class="dashboard-grid"><section class="card chart-card"><div class="section-title"><h3>设备类型分布</h3><span class="muted">共 {{overview?.devices.total||0}} 个</span></div><div v-if="!overview?.devices.by_type.length" class="inline-empty">暂无设备数据</div><div v-else class="bar-list"><div v-for="item in overview.devices.by_type" :key="item.type"><span>{{item.type}}</span><div><i :style="{width:`${item.count/maxDevice*100}%`}"></i></div><strong>{{item.count}}</strong></div></div></section>
<section class="card chart-card"><div class="section-title"><h3>资产状态分布</h3><span class="muted">生命周期状态</span></div><div v-if="!assets?.by_status.length" class="inline-empty">暂无资产数据</div><div v-else class="bar-list asset-bars"><div v-for="item in assets.by_status" :key="item.status"><span>{{statusName[item.status||'']||item.status}}</span><div><i :style="{width:`${item.count/maxAsset*100}%`}"></i></div><strong>{{item.count}}</strong></div></div></section>
<section class="card chart-card wide"><div class="section-title"><h3>工单状态</h3><span class="muted">实时统计</span></div><div v-if="!operations?.by_status?.length" class="inline-empty">暂无工单数据</div><div v-else class="status-summary"><div v-for="item in operations.by_status" :key="item.status"><strong>{{item.count}}</strong><span>{{statusName[item.status||'']||item.status}}</span></div></div></section></div></template></section></template>
