<script setup lang="ts">
import { onMounted, ref } from 'vue'; import { useRouter } from 'vue-router'; import { IconLeft, IconPlus } from '@arco-design/web-vue/es/icon'; import { importApi } from '../api/imports'; import type { ImportError, ImportJob } from '../types'
const router = useRouter(); const jobs = ref<ImportJob[]>([]), loading = ref(false), total = ref(0), page = ref(1), selectedJob = ref<ImportJob | null>(null), errors = ref<ImportError[]>([]), errorsTotal = ref(0), loadingErrors = ref(false), errorsVisible = ref(false); const pageSize = 20
const statusText: Record<string, string> = { PREVIEWED: '已预览', EXECUTING: '执行中', SUCCEEDED: '成功', FAILED: '失败' }; const statusColor = (value: string) => ({ PREVIEWED: 'blue', EXECUTING: 'orange', SUCCEEDED: 'green', FAILED: 'red' }[value] || 'gray'); const formatTime = (value: string) => new Date(value).toLocaleString('zh-CN')
async function load() { loading.value = true; try { const { data } = await importApi.history({ page: page.value, page_size: pageSize }); jobs.value = data.items; total.value = data.total } finally { loading.value = false } }
async function showErrors(job: ImportJob) { selectedJob.value = job; errorsVisible.value = true; loadingErrors.value = true; errors.value = []; try { const { data } = await importApi.errors(job.id, { page: 1, page_size: 200 }); errors.value = data.items; errorsTotal.value = data.total } finally { loadingErrors.value = false } } onMounted(load)
</script>
<template><section class="page arco-page"><header class="page-header"><div><p class="eyebrow">数据接入</p><h1>导入历史</h1><p class="muted">查看导入任务状态和校验错误</p></div><a-space><a-button @click="router.push('/import')"><template #icon><IconLeft /></template>返回数据导入</a-button><a-button type="primary" @click="router.push('/import')"><template #icon><IconPlus /></template>新建导入</a-button></a-space></header>
  <a-card class="arco-table-card" :bordered="false"><a-table :data="jobs" :loading="loading" :pagination="false" row-key="id" :scroll="{ x: 1000 }"><template #columns><a-table-column title="文件名" data-index="filename" :width="220" /><a-table-column title="格式" data-index="format" :width="90" /><a-table-column title="创建时间" :width="180"><template #cell="{ record }">{{ formatTime(record.created_at) }}</template></a-table-column><a-table-column title="状态" :width="100"><template #cell="{ record }"><a-tag :color="statusColor(record.status)" bordered>{{ statusText[record.status] || record.status }}</a-tag></template></a-table-column><a-table-column title="总数" data-index="total_rows" :width="90" /><a-table-column title="成功" data-index="success_count" :width="90" /><a-table-column title="失败" data-index="failed_count" :width="90" /><a-table-column title="操作" fixed="right" :width="110"><template #cell="{ record }"><a-button type="text" size="small" @click="showErrors(record)">查看错误</a-button></template></a-table-column></template><template #empty><a-empty description="暂无导入记录" /></template></a-table><div class="arco-pagination"><span>共 {{ total }} 条</span><a-pagination :current="page" :page-size="pageSize" :total="total" :show-total="false" @change="(value) => { page = value; load() }" /></div></a-card>
  <a-modal v-model:visible="errorsVisible" :title="`错误详情 · ${selectedJob?.filename || ''}`" width="800px" :footer="false"><a-table :data="errors" :loading="loadingErrors" :pagination="false" :scroll="{ x: 700, y: 420 }"><template #columns><a-table-column title="行号" data-index="row" :width="80" /><a-table-column title="字段" :width="130"><template #cell="{ record }">{{ record.field || '—' }}</template></a-table-column><a-table-column title="错误类型" data-index="error_type" :width="160" /><a-table-column title="错误信息" data-index="message" /></template><template #empty><a-empty description="该任务没有错误记录" /></template></a-table><p class="modal-table-total">共 {{ errorsTotal }} 条错误</p></a-modal>
</section></template>
