<script setup lang="ts">
import { onMounted, ref } from 'vue'; import { useRouter } from 'vue-router'; import { IconLeft, IconPlus } from '@arco-design/web-vue/es/icon'; import { assetApi } from '../api/assets'; import { loadCatalogs } from '../stores/catalog'; import type { InventoryLocation } from '../types'
const router = useRouter(); const locations = ref<InventoryLocation[]>([]), submitting = ref(false), loading = ref(false), visible = ref(false); const form = ref({ name: '', warehouse: '', shelf: '', location_code: '', description: '' })
async function load() { loading.value = true; try { locations.value = (await assetApi.locations()).data.items } finally { loading.value = false } }
async function create() { if (!form.value.name || !form.value.warehouse || !form.value.location_code) return; submitting.value = true; try { await assetApi.createLocation({ ...form.value, shelf: form.value.shelf || null, description: form.value.description || null }); await Promise.all([load(), loadCatalogs(true)]); form.value = { name: '', warehouse: '', shelf: '', location_code: '', description: '' }; visible.value = false } finally { submitting.value = false } }
onMounted(load)
</script>
<template><section class="page arco-page"><header class="page-header"><div><p class="eyebrow">库存管理</p><h1>库存位置</h1><p class="muted">维护仓库、货架与库存位置编码</p></div><a-space><a-button @click="router.push('/assets')"><template #icon><IconLeft /></template>返回资产台账</a-button><a-button type="primary" @click="visible = true"><template #icon><IconPlus /></template>新建位置</a-button></a-space></header>
  <a-card class="arco-table-card" :bordered="false"><a-table :data="locations" :loading="loading" :pagination="false" row-key="id"><template #columns><a-table-column title="位置名称" data-index="name" :width="180" /><a-table-column title="仓库" data-index="warehouse" :width="180" /><a-table-column title="货架" :width="140"><template #cell="{ record }">{{ record.shelf || '—' }}</template></a-table-column><a-table-column title="位置编码" data-index="location_code" :width="180" /><a-table-column title="说明"><template #cell="{ record }">{{ record.description || '—' }}</template></a-table-column></template><template #empty><a-empty description="暂无可展示的库存位置" /></template></a-table><div class="arco-pagination"><span>共 {{ locations.length }} 个位置</span></div></a-card>
  <a-modal v-model:visible="visible" title="新建库存位置" :ok-loading="submitting" ok-text="创建位置" cancel-text="取消" @ok="create"><a-form :model="form" layout="vertical"><div class="modal-form-grid"><a-form-item label="位置名称" required><a-input v-model="form.name" /></a-form-item><a-form-item label="仓库" required><a-input v-model="form.warehouse" /></a-form-item><a-form-item label="货架"><a-input v-model="form.shelf" /></a-form-item><a-form-item label="位置编码" required><a-input v-model="form.location_code" /></a-form-item></div><a-form-item label="说明"><a-textarea v-model="form.description" :auto-size="{ minRows: 2, maxRows: 4 }" /></a-form-item></a-form></a-modal>
</section></template>
