<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { useRoute } from 'vue-router'
import { knowledgeApi } from '../api/knowledge'
import type { InfrastructureObject, KnowledgeArticleDetail } from '../types'
const route=useRoute(),article=ref<KnowledgeArticleDetail|null>(null),objects=ref<InfrastructureObject[]>([]),selected=ref<string[]>([]),reason=ref(''),file=ref<File|null>(null),loading=ref(true),working=ref(false)
const id=computed(()=>String(route.params.id)), availableObjects=computed(()=>objects.value.filter(item=>!article.value?.links.some(link=>link.related_id===item.id)))
const typeName:Record<string,string>={SOP:'标准操作流程',TROUBLESHOOTING:'故障排查',FAQ:'常见问题',BEST_PRACTICE:'最佳实践'},statusName:Record<string,string>={DRAFT:'草稿',UNDER_REVIEW:'审核中',PUBLISHED:'已发布',ARCHIVED:'已归档'}
function format(v:string|null){return v?new Date(v).toLocaleString('zh-CN'):'—'} function size(v:number){return v<1024?`${v} B`:v<1048576?`${(v/1024).toFixed(1)} KB`:`${(v/1048576).toFixed(1)} MB`}
async function load(){const {data}=await knowledgeApi.get(id.value);article.value=data}
async function publish(){if(!window.confirm('确认发布这篇文章吗？'))return;working.value=true;try{await knowledgeApi.publish(id.value);await load()}finally{working.value=false}}
async function upload(){if(!file.value)return;working.value=true;try{await knowledgeApi.upload(id.value,file.value);file.value=null;await load()}finally{working.value=false}}
async function link(){if(!selected.value.length)return;working.value=true;try{await knowledgeApi.linkObjects(id.value,selected.value,reason.value);selected.value=[];reason.value='';await load()}finally{working.value=false}}
function chooseFile(event:Event){file.value=(event.target as HTMLInputElement).files?.[0]||null}
async function download(attachmentId:string,fileName:string){const {data}=await knowledgeApi.downloadAttachment(id.value,attachmentId);const url=URL.createObjectURL(data);const anchor=document.createElement('a');anchor.href=url;anchor.download=fileName;anchor.click();URL.revokeObjectURL(url)}
onMounted(async()=>{try{const [,o]=await Promise.all([load(),knowledgeApi.objects()]);objects.value=o.data.items}finally{loading.value=false}})
</script>
<template><section class="page narrow"><RouterLink class="back" to="/knowledge">← 返回知识库</RouterLink><div v-if="loading" class="card empty">正在加载文章…</div><template v-else-if="article"><header class="page-header"><div><p class="eyebrow">{{typeName[article.type]}}</p><div class="title-row"><h1>{{article.title}}</h1><span class="status" :class="article.status.toLowerCase()">{{statusName[article.status]}}</span></div><p class="muted">版本 {{article.version}} · 更新于 {{format(article.updated_at)}}</p></div><button v-if="article.status==='DRAFT'" class="button primary" :disabled="working" @click="publish">发布文章</button></header><article class="card article-card"><div v-if="article.tags?.length" class="article-tags"><span v-for="tag in article.tags" :key="tag">{{tag}}</span></div><div class="article-content">{{article.content}}</div></article><div class="knowledge-detail-grid"><section class="card"><div class="section-title"><h3>附件</h3><span class="muted">{{article.attachments.length}} 个</span></div><div v-if="!article.attachments.length" class="inline-empty">暂无附件</div><div v-else class="attachment-list"><div v-for="item in article.attachments" :key="item.id"><strong>{{item.file_name}}</strong><span>{{size(item.file_size)}} · {{format(item.created_at)}} · <button class="link" @click="download(item.id,item.file_name)">下载</button></span></div></div><form class="inline-upload" @submit.prevent="upload"><label class="file-picker"><input type="file" @change="chooseFile" /><span>{{file?.name||'选择附件'}}</span></label><button class="button" :disabled="!file||working">上传</button></form></section><section class="card"><div class="section-title"><h3>关联对象</h3><span class="muted">{{article.links.length}} 个</span></div><div v-if="!article.links.length" class="inline-empty">暂无关联对象</div><div v-else class="linked-list"><RouterLink v-for="link in article.links" :key="link.id" :to="`/objects/${link.related_id}`"><strong>{{link.object_name||objects.find(item=>item.id===link.related_id)?.name||link.related_id}}</strong><span>{{link.relation_reason||'未填写关联说明'}}</span></RouterLink></div><form class="link-form" @submit.prevent="link"><label><span>选择对象（可多选）</span><select v-model="selected" multiple size="5"><option v-for="item in availableObjects" :key="item.id" :value="item.id">{{item.name}} · {{item.serial_number||item.model||'无编号'}}</option></select></label><label><span>关联说明</span><input v-model="reason" maxlength="255" placeholder="可选" /></label><button class="button" :disabled="!selected.length||working">添加关联</button></form></section></div></template></section></template>
