<script setup lang="ts">
import { computed,onMounted,ref } from 'vue'
import { useRouter } from 'vue-router'
import { IconPlus,IconRobot,IconSearch } from '@arco-design/web-vue/es/icon'
import { knowledgeApi,type AskResponse } from '../api/knowledge'
import type { KnowledgeArticle } from '../types'
const router=useRouter(),items=ref<KnowledgeArticle[]>([]),loading=ref(false),total=ref(0),page=ref(1),type=ref(''),status=ref(''),pageSize=20,question=ref(''),asking=ref(false),askResult=ref<AskResponse|null>(null)
const totalPages=computed(()=>Math.max(1,Math.ceil(total.value/pageSize))),typeName:Record<string,string>={SOP:'标准操作流程',TROUBLESHOOTING:'故障排查',FAQ:'常见问题',BEST_PRACTICE:'最佳实践'},statusName:Record<string,string>={DRAFT:'草稿',UNDER_REVIEW:'审核中',PUBLISHED:'已发布',ARCHIVED:'已归档'}
const statusColor=(value:string)=>({DRAFT:'gray',UNDER_REVIEW:'orange',PUBLISHED:'green',ARCHIVED:'gray'}[value]||'gray')
async function load(){loading.value=true;try{const {data}=await knowledgeApi.list({page:page.value,page_size:pageSize,type:type.value||undefined,status:status.value||undefined});items.value=data.items;total.value=data.total}finally{loading.value=false}}
function filter(){page.value=1;void load()} function reset(){type.value='';status.value='';filter()} function changePage(value:number){page.value=value;void load()}
async function askQuestion(){const q=question.value.trim();if(!q)return;asking.value=true;askResult.value=null;try{askResult.value=(await knowledgeApi.ask(q)).data}finally{asking.value=false}}
const format=(v:string)=>new Date(v).toLocaleString('zh-CN')
onMounted(load)
</script>
<template><section class="page arco-page"><header class="page-header"><div><p class="eyebrow">知识中心</p><h1>知识库</h1><p class="muted">沉淀基础设施运维经验与标准流程</p></div><a-button type="primary" @click="router.push('/knowledge/new')"><template #icon><IconPlus/></template>新建文章</a-button></header>
<a-card class="knowledge-ai-card" :bordered="false"><template #title><span class="card-title-icon"><IconRobot/>AI 问答</span></template><a-textarea v-model="question" :auto-size="{minRows:3,maxRows:8}" placeholder="输入您的问题…" :disabled="asking"/><div class="ask-actions"><a-button type="primary" :loading="asking" :disabled="!question.trim()" @click="askQuestion">提问</a-button></div><a-alert v-if="askResult&&!askResult.configured" type="warning">大语言模型未配置，无法生成 AI 回答，请联系管理员配置。</a-alert><template v-else-if="askResult"><a-card v-if="askResult.answer" class="answer-card" title="AI 回答" :bordered="false"><a-typography-paragraph>{{askResult.answer}}</a-typography-paragraph></a-card><div v-if="askResult.sources.length" class="source-list"><h4>参考来源</h4><a-list :bordered="false"><a-list-item v-for="source in askResult.sources" :key="source.id"><a-list-item-meta :title="source.title" :description="source.summary" @click="router.push(`/knowledge/${source.id}`)"><template #avatar><a-tag color="arcoblue">{{typeName[source.type]||source.type}}</a-tag></template></a-list-item-meta></a-list-item></a-list></div><a-empty v-else-if="!askResult.answer" description="未找到相关知识文章"/></template></a-card>
<a-card class="arco-filter-card" :bordered="false"><a-form :model="{}" layout="inline" @submit.prevent="filter"><a-form-item label="文章分类"><a-select v-model="type" allow-clear placeholder="全部分类"><a-option value="">全部分类</a-option><a-option v-for="(name,value) in typeName" :key="value" :value="value">{{name}}</a-option></a-select></a-form-item><a-form-item label="发布状态"><a-select v-model="status" allow-clear placeholder="全部状态"><a-option value="">全部状态</a-option><a-option v-for="(name,value) in statusName" :key="value" :value="value">{{name}}</a-option></a-select></a-form-item><a-form-item><a-space><a-button type="primary" html-type="submit"><template #icon><IconSearch/></template>查询</a-button><a-button @click="reset">重置</a-button></a-space></a-form-item></a-form></a-card>
<a-card class="arco-table-card" :bordered="false"><a-table :data="items" :loading="loading" :pagination="false" row-key="id" @row-click="record=>router.push(`/knowledge/${record.id}`)"><template #columns><a-table-column title="标题" data-index="title"><template #cell="{record}"><a-link class="object-name">{{record.title}}</a-link></template></a-table-column><a-table-column title="分类"><template #cell="{record}">{{typeName[record.type]||record.type}}</template></a-table-column><a-table-column title="状态"><template #cell="{record}"><a-tag :color="statusColor(record.status)">{{statusName[record.status]||record.status}}</a-tag></template></a-table-column><a-table-column title="标签"><template #cell="{record}"><a-space wrap><a-tag v-for="tag in record.tags" :key="tag">{{tag}}</a-tag><span v-if="!record.tags?.length">—</span></a-space></template></a-table-column><a-table-column title="创建时间"><template #cell="{record}">{{format(record.created_at)}}</template></a-table-column><a-table-column title="更新时间"><template #cell="{record}">{{format(record.updated_at)}}</template></a-table-column><a-table-column title="操作" :width="80"><template #cell="{record}"><a-button type="text" size="small" @click.stop="router.push(`/knowledge/${record.id}`)">详情</a-button></template></a-table-column></template><template #empty><a-empty class="atlas-empty-guide" description="暂无知识文章，可沉淀第一篇运维经验"><a-button type="primary" @click="router.push('/knowledge/new')">新建文章</a-button></a-empty></template></a-table><div class="arco-pagination"><span>共 {{total}} 条，第 {{page}} / {{totalPages}} 页</span><a-pagination :current="page" :page-size="pageSize" :total="total" @change="changePage"/></div></a-card></section></template>
