<script setup lang="ts">
import { computed,onMounted,ref } from 'vue'
import { useRoute,useRouter } from 'vue-router'
import { Modal } from '@arco-design/web-vue'
import { IconDownload,IconEdit,IconLeft,IconLink,IconUpload } from '@arco-design/web-vue/es/icon'
import { knowledgeApi } from '../api/knowledge'
import type { InfrastructureObject,KnowledgeArticleDetail } from '../types'
const route=useRoute(),router=useRouter(),article=ref<KnowledgeArticleDetail|null>(null),objects=ref<InfrastructureObject[]>([]),selected=ref<string[]>([]),reason=ref(''),file=ref<File|null>(null),loading=ref(true),working=ref(false),id=computed(()=>String(route.params.id)),availableObjects=computed(()=>objects.value.filter(item=>!article.value?.links.some(link=>link.related_id===item.id)))
const typeName:Record<string,string>={SOP:'标准操作流程',TROUBLESHOOTING:'故障排查',FAQ:'常见问题',BEST_PRACTICE:'最佳实践'},statusName:Record<string,string>={DRAFT:'草稿',UNDER_REVIEW:'审核中',PUBLISHED:'已发布',ARCHIVED:'已归档'},statusColor=(value:string)=>({DRAFT:'gray',UNDER_REVIEW:'orange',PUBLISHED:'green',ARCHIVED:'gray'}[value]||'gray')
const format=(v:string|null)=>v?new Date(v).toLocaleString('zh-CN'):'—',size=(v:number)=>v<1024?`${v} B`:v<1048576?`${(v/1024).toFixed(1)} KB`:`${(v/1048576).toFixed(1)} MB`
async function load(){article.value=(await knowledgeApi.get(id.value)).data}
function publish(){Modal.confirm({title:'发布文章',content:'确认发布这篇文章吗？',okText:'确认发布',cancelText:'取消',onOk:async()=>{working.value=true;try{await knowledgeApi.publish(id.value);await load()}finally{working.value=false}}})}
async function upload(){if(!file.value)return;working.value=true;try{await knowledgeApi.upload(id.value,file.value);file.value=null;await load()}finally{working.value=false}}
async function link(){if(!selected.value.length)return;working.value=true;try{await knowledgeApi.linkObjects(id.value,selected.value,reason.value);selected.value=[];reason.value='';await load()}finally{working.value=false}}
function chooseFile(event:Event){file.value=(event.target as HTMLInputElement).files?.[0]||null}
async function download(attachmentId:string,fileName:string){const {data}=await knowledgeApi.downloadAttachment(id.value,attachmentId),url=URL.createObjectURL(data),anchor=document.createElement('a');anchor.href=url;anchor.download=fileName;anchor.click();URL.revokeObjectURL(url)}
onMounted(async()=>{try{const [,o]=await Promise.all([load(),knowledgeApi.objects()]);objects.value=o.data.items}finally{loading.value=false}})
</script>
<template><section class="page arco-page knowledge-detail-page"><a-button class="detail-back" type="text" @click="router.push('/knowledge')"><template #icon><IconLeft/></template>返回知识库</a-button><a-spin class="detail-spin" :loading="loading"><template v-if="article"><header class="page-header"><div><p class="eyebrow">{{typeName[article.type]}}</p><div class="title-row"><h1>{{article.title}}</h1><a-tag :color="statusColor(article.status)">{{statusName[article.status]}}</a-tag></div><p class="muted">版本 {{article.version}} · 更新于 {{format(article.updated_at)}}</p></div><a-space><a-tooltip content="当前接口暂不支持编辑文章"><a-button disabled><template #icon><IconEdit/></template>编辑文章</a-button></a-tooltip><a-button v-if="article.status==='DRAFT'" type="primary" :loading="working" @click="publish">发布文章</a-button></a-space></header>
<a-card class="article-typography-card" :bordered="false"><a-space v-if="article.tags?.length" wrap><a-tag v-for="tag in article.tags" :key="tag" color="arcoblue">{{tag}}</a-tag></a-space><a-divider v-if="article.tags?.length"/><a-typography><a-typography-paragraph class="article-body">{{article.content}}</a-typography-paragraph></a-typography></a-card>
<div class="knowledge-detail-grid"><a-card title="附件" :bordered="false"><template #extra><a-tag>{{article.attachments.length}} 个</a-tag></template><a-table :data="article.attachments" :pagination="false" row-key="id"><template #columns><a-table-column title="文件名" data-index="file_name"/><a-table-column title="大小"><template #cell="{record}">{{size(record.file_size)}}</template></a-table-column><a-table-column title="上传时间"><template #cell="{record}">{{format(record.created_at)}}</template></a-table-column><a-table-column title="操作"><template #cell="{record}"><a-button type="text" @click="download(record.id,record.file_name)"><template #icon><IconDownload/></template>下载</a-button></template></a-table-column></template><template #empty><a-empty description="暂无附件"/></template></a-table><div class="detail-inline-form"><label class="file-trigger"><input type="file" @change="chooseFile"/><a-button><template #icon><IconUpload/></template>{{file?.name||'选择附件'}}</a-button></label><a-button type="primary" :disabled="!file" :loading="working" @click="upload">上传</a-button></div></a-card>
<a-card title="关联对象" :bordered="false"><template #extra><a-tag>{{article.links.length}} 个</a-tag></template><a-table :data="article.links" :pagination="false" row-key="id"><template #columns><a-table-column title="对象"><template #cell="{record}"><a-link @click="router.push(`/objects/${record.related_id}`)">{{record.object_name||objects.find(item=>item.id===record.related_id)?.name||record.related_id}}</a-link></template></a-table-column><a-table-column title="关联说明"><template #cell="{record}">{{record.relation_reason||'—'}}</template></a-table-column></template><template #empty><a-empty description="暂无关联对象"/></template></a-table><a-form :model="{}" layout="vertical" class="link-object-form"><a-form-item label="选择对象（可多选）"><a-select v-model="selected" multiple placeholder="请选择对象"><a-option v-for="item in availableObjects" :key="item.id" :value="item.id">{{item.name}} · {{item.serial_number||item.model||'无编号'}}</a-option></a-select></a-form-item><a-form-item label="关联说明"><a-input v-model="reason" :max-length="255" placeholder="可选"/></a-form-item><a-button type="primary" :disabled="!selected.length" :loading="working" @click="link"><template #icon><IconLink/></template>添加关联</a-button></a-form></a-card></div></template></a-spin></section></template>
