<script setup lang="ts">
import { computed,onMounted,reactive,ref } from 'vue'
import { useRoute,useRouter } from 'vue-router'
import { Message } from '@arco-design/web-vue'
import { IconLeft } from '@arco-design/web-vue/es/icon'
import { objectApi } from '../api/objects'
import type { ManagementScope,ObjectPayload,ObjectStatus,ObjectType,Ownership } from '../types'
const route=useRoute(),router=useRouter(),id=computed(()=>route.params.id as string|undefined),types=ref<ObjectType[]>([]),saving=ref(false),loading=ref(false),version=ref(1),specText=ref('{}'),validationError=ref('')
const form=reactive({object_type_id:'',name:'',serial_number:'',asset_number:'',manufacturer:'',model:'',firmware_version:'',hardware_generation:'',status:'PLANNED' as ObjectStatus,ownership:'OWNED' as Ownership,management_scope:'NO_ACCESS' as ManagementScope,owner_org_id:'',operator_org_id:'',maintainer_org_id:'',deployed_location_id:''})
const title=computed(()=>id.value?'编辑对象':'新建对象'),nullable=(value:string)=>value.trim()||null
async function submit(){validationError.value='';let spec_data:Record<string,unknown>;try{const parsed:unknown=JSON.parse(specText.value||'{}');if(!parsed||Array.isArray(parsed)||typeof parsed!=='object')throw new Error();spec_data=parsed as Record<string,unknown>}catch{validationError.value='技术规格必须是有效的 JSON 对象';return}const payload:ObjectPayload={...form,serial_number:nullable(form.serial_number),asset_number:nullable(form.asset_number),manufacturer:nullable(form.manufacturer),model:nullable(form.model),firmware_version:nullable(form.firmware_version),hardware_generation:nullable(form.hardware_generation),owner_org_id:nullable(form.owner_org_id),operator_org_id:nullable(form.operator_org_id),maintainer_org_id:nullable(form.maintainer_org_id),deployed_location_id:nullable(form.deployed_location_id),spec_data};saving.value=true;try{const response=id.value?await objectApi.update(id.value,version.value,payload):await objectApi.create(payload);Message.success('对象保存成功');await router.push(`/objects/${response.data.id}`)}finally{saving.value=false}}
onMounted(async()=>{loading.value=true;try{types.value=(await objectApi.types()).data.items;if(!id.value)return;const {data}=await objectApi.get(id.value);version.value=data.version;Object.assign(form,Object.fromEntries(Object.keys(form).map(key=>[key,(data as unknown as Record<string,unknown>)[key]??''])));specText.value=JSON.stringify(data.spec_data,null,2)}finally{loading.value=false}})
</script>
<template><section class="page arco-page form-page"><a-button class="detail-back" type="text" @click="router.push(id?`/objects/${id}`:'/objects')"><template #icon><IconLeft /></template>返回</a-button><header class="page-header"><div><p class="eyebrow">基础设施对象</p><h1>{{title}}</h1><p class="muted">维护对象基础属性、管理边界与技术规格</p></div></header><a-spin :loading="loading"><a-card class="arco-form-card" :bordered="false"><a-form :model="form" layout="vertical" @submit-success="submit"><h3 class="form-section-title">基础信息</h3><div class="object-form-grid">
<a-form-item field="object_type_id" label="对象类型" required><a-select v-model="form.object_type_id" :disabled="!!id" placeholder="请选择"><a-option v-for="item in types" :key="item.id" :value="item.id">{{item.display_name||item.name}}</a-option></a-select></a-form-item><a-form-item field="name" label="名称" required><a-input v-model.trim="form.name" :max-length="255"/></a-form-item>
<a-form-item label="序列号"><a-input v-model.trim="form.serial_number"/></a-form-item><a-form-item label="资产编号"><a-input v-model.trim="form.asset_number"/></a-form-item><a-form-item label="制造商"><a-input v-model.trim="form.manufacturer"/></a-form-item><a-form-item label="型号"><a-input v-model.trim="form.model"/></a-form-item><a-form-item label="固件版本"><a-input v-model.trim="form.firmware_version"/></a-form-item><a-form-item label="硬件代际"><a-input v-model.trim="form.hardware_generation"/></a-form-item>
<a-form-item label="状态"><a-select v-model="form.status"><a-option value="PLANNED">计划中</a-option><a-option value="ACTIVE">运行中</a-option><a-option value="INACTIVE">未启用</a-option><a-option value="MAINTENANCE">维护中</a-option><a-option value="RETIRED">已退役</a-option></a-select></a-form-item><a-form-item label="所有权"><a-select v-model="form.ownership"><a-option value="OWNED">自有</a-option><a-option value="CUSTOMER_OWNED">客户所有</a-option><a-option value="THIRD_PARTY">第三方</a-option></a-select></a-form-item><a-form-item label="管理范围"><a-select v-model="form.management_scope"><a-option value="FULL_CONTROL">完全控制</a-option><a-option value="HARDWARE_ONLY">仅硬件</a-option><a-option value="MAINTENANCE_ONLY">仅维保</a-option><a-option value="NO_ACCESS">无访问权</a-option></a-select></a-form-item>
<a-form-item label="所有者组织 ID"><a-input v-model.trim="form.owner_org_id" placeholder="UUID（可选）"/></a-form-item><a-form-item label="运营组织 ID"><a-input v-model.trim="form.operator_org_id" placeholder="UUID（可选）"/></a-form-item><a-form-item label="维保组织 ID"><a-input v-model.trim="form.maintainer_org_id" placeholder="UUID（可选）"/></a-form-item><a-form-item label="部署位置对象 ID"><a-input v-model.trim="form.deployed_location_id" placeholder="UUID（可选）"/></a-form-item></div><a-divider/><h3 class="form-section-title">技术规格</h3><a-form-item label="JSON 规格数据" :validate-status="validationError?'error':undefined" :help="validationError"><a-textarea v-model="specText" :auto-size="{minRows:12,maxRows:24}" placeholder="请输入 JSON 对象"/></a-form-item><div class="arco-form-actions"><a-button @click="router.push(id?`/objects/${id}`:'/objects')">取消</a-button><a-button type="primary" html-type="submit" :loading="saving">保存对象</a-button></div></a-form></a-card></a-spin></section></template>
