<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { IconEdit, IconLeft } from '@arco-design/web-vue/es/icon'
import { objectApi } from '../api/objects'
import { loadCatalogs, useCatalog } from '../stores/catalog'
import type { InfrastructureObject, ObjectDetail, ObjectHistory, ObjectStatus, Relationship, RelationshipType } from '../types'
const route=useRoute(),router=useRouter(),id=route.params.id as string
const object=ref<ObjectDetail>(),histories=ref<ObjectHistory[]>([]),relations=ref<Relationship[]>([]),objectNames=ref<Record<string,string>>({}),relationTypes=ref<Record<string,RelationshipType>>({}),loading=ref(true)
const {organizationMap,locationMap}=useCatalog()
const ownershipName:Record<string,string>={OWNED:'自有',CUSTOMER_OWNED:'客户所有',THIRD_PARTY:'第三方'},scopeName:Record<string,string>={FULL_CONTROL:'完全控制',HARDWARE_ONLY:'仅硬件',MAINTENANCE_ONLY:'仅维保',NO_ACCESS:'无访问权'},statusName:Record<string,string>={PLANNED:'计划中',ACTIVE:'运行中',INACTIVE:'未启用',MAINTENANCE:'维护中',RETIRED:'已退役'}
const statusLabel=(value:ObjectStatus)=>statusName[value]||value,statusColor=(value:ObjectStatus)=>({PLANNED:'blue',ACTIVE:'green',INACTIVE:'gray',MAINTENANCE:'orange',RETIRED:'gray'}[value]||'gray')
const info=computed(()=>object.value?[['名称',object.value.name],['对象类型',object.value.object_type.display_name||object.value.object_type.name],['状态',statusLabel(object.value.status)],['制造商',object.value.manufacturer],['型号',object.value.model],['序列号',object.value.serial_number],['资产编号',object.value.asset_number],['固件版本',object.value.firmware_version],['所有权',ownershipName[object.value.ownership]],['管理范围',scopeName[object.value.management_scope]],['所有者组织',organizationMap.value[object.value.owner_org_id||'']],['部署位置',locationMap.value[object.value.deployed_location_id||'']],['更新时间',new Date(object.value.updated_at).toLocaleString('zh-CN')]]:[])
function display(value:unknown){if(value==null||value==='')return '—';return typeof value==='object'?JSON.stringify(value,null,2):String(value)}
function changedFields(item:ObjectHistory){const before=item.before_data||{},after=item.after_data||{};return Array.from(new Set([...Object.keys(before),...Object.keys(after)])).filter(key=>JSON.stringify(before[key])!==JSON.stringify(after[key]))}
function relationLabel(item:Relationship){return relationTypes.value[item.relationship_type_id]?.display_name||relationTypes.value[item.relationship_type_id]?.name||'关联'}
function objectName(objectId:string){return objectId===id?object.value?.name||objectId:objectNames.value[objectId]||objectId}
onMounted(async()=>{try{const [detail,history,outgoing,incoming,typeResponse,allObjects]=await Promise.all([objectApi.get(id),objectApi.history(id),objectApi.relations({source_object_id:id}),objectApi.relations({target_object_id:id}),objectApi.relationshipTypes(),objectApi.list({page:1,page_size:200}),loadCatalogs()]);object.value=detail.data;histories.value=history.data.items;relations.value=[...outgoing.data.items,...incoming.data.items.filter(item=>!outgoing.data.items.some(other=>other.id===item.id))];relationTypes.value=Object.fromEntries(typeResponse.data.items.map(item=>[item.id,item]));objectNames.value=Object.fromEntries(allObjects.data.items.map((item:InfrastructureObject)=>[item.id,item.name]))}finally{loading.value=false}})
</script>
<template><section class="page arco-page"><a-spin class="detail-spin" :loading="loading"><template v-if="object"><a-button class="detail-back" type="text" @click="router.push('/objects')"><template #icon><IconLeft /></template>返回对象列表</a-button><header class="page-header"><div><div class="title-row"><h1>{{object.name}}</h1><a-tag :color="statusColor(object.status)" bordered>{{statusLabel(object.status)}}</a-tag></div><p class="muted">{{object.object_type.display_name||object.object_type.name}} · {{object.manufacturer||'未知制造商'}} {{object.model||''}}</p></div><a-button type="primary" @click="router.push(`/objects/${id}/edit`)"><template #icon><IconEdit /></template>编辑对象</a-button></header>
<div class="object-stat-grid"><a-card :bordered="false"><a-statistic title="关联关系" :value="object.relationship_summary.total" /></a-card><a-card :bordered="false"><a-statistic title="规格字段" :value="Object.keys(object.spec_data).length" /></a-card><a-card :bordered="false"><a-statistic title="数据版本" :value="object.version" prefix="v" /></a-card></div>
<a-tabs default-active-key="basic" class="object-detail-tabs"><a-tab-pane key="basic" title="基础信息"><a-card :bordered="false"><a-descriptions :column="2" bordered><a-descriptions-item v-for="([label,value]) in info" :key="String(label)" :label="String(label)">{{display(value)}}</a-descriptions-item></a-descriptions></a-card></a-tab-pane><a-tab-pane key="spec" title="技术规格"><a-card :bordered="false"><a-empty v-if="!Object.keys(object.spec_data).length" description="暂无规格数据"/><a-collapse v-else :default-active-key="['spec']"><a-collapse-item key="spec" header="规格 JSON"><pre class="spec-json">{{JSON.stringify(object.spec_data,null,2)}}</pre></a-collapse-item></a-collapse></a-card></a-tab-pane>
<a-tab-pane key="relations" :title="`关联关系 (${relations.length})`"><a-card class="arco-table-card" :bordered="false"><a-table :data="relations" :pagination="false" row-key="id"><template #columns><a-table-column title="源对象"><template #cell="{record}"><a-link @click="router.push(`/objects/${record.source_object_id}`)">{{objectName(record.source_object_id)}}</a-link></template></a-table-column><a-table-column title="关系类型"><template #cell="{record}"><a-tag color="arcoblue">{{relationLabel(record)}}</a-tag></template></a-table-column><a-table-column title="目标对象"><template #cell="{record}"><a-link @click="router.push(`/objects/${record.target_object_id}`)">{{objectName(record.target_object_id)}}</a-link></template></a-table-column><a-table-column title="可信度" data-index="confidence"/><a-table-column title="数据来源" data-index="data_source"/></template><template #empty><a-empty description="暂无关联关系"/></template></a-table></a-card></a-tab-pane>
<a-tab-pane key="history" :title="`变更历史 (${histories.length})`"><a-card :bordered="false"><a-empty v-if="!histories.length" description="暂无历史记录"/><a-timeline v-else><a-timeline-item v-for="item in histories" :key="item.id" :label="new Date(item.created_at).toLocaleString('zh-CN')"><strong>{{item.change_type}}</strong><p class="timeline-operator">来源：{{item.source}}<template v-if="item.operator"> · 操作人：{{item.operator}}</template></p><a-collapse v-if="changedFields(item).length" class="history-changes"><a-collapse-item key="changes" :header="`查看变更（${changedFields(item).length} 项）`"><div v-for="field in changedFields(item)" :key="field" class="change-row"><code>{{field}}</code><span>{{display(item.before_data?.[field])}}</span><b>→</b><span>{{display(item.after_data?.[field])}}</span></div></a-collapse-item></a-collapse></a-timeline-item></a-timeline></a-card></a-tab-pane></a-tabs></template></a-spin></section></template>
