<script setup lang="ts">
import { computed,onMounted,reactive,ref } from 'vue'
import { IconEdit,IconPlus,IconSearch } from '@arco-design/web-vue/es/icon'
import { adminApi } from '../api/admin'
import { loadCatalogs } from '../stores/catalog'
import type { Organization,OrganizationType } from '../types'
const items=ref<Organization[]>([]),total=ref(0),page=ref(1),search=ref(''),loading=ref(false),saving=ref(false),modal=ref(false),editing=ref<Organization|null>(null),pageSize=20,totalPages=computed(()=>Math.max(1,Math.ceil(total.value/pageSize))),form=reactive({name:'',org_type:'INTERNAL' as OrganizationType,is_active:true}),typeName:Record<OrganizationType,string>={INTERNAL:'内部组织',CUSTOMER:'客户',VENDOR:'供应商'}
async function load(){loading.value=true;try{const {data}=await adminApi.organizations({search:search.value||undefined,page:page.value,page_size:pageSize});items.value=data.items;total.value=data.total}finally{loading.value=false}}
function query(){page.value=1;void load()} function changePage(value:number){page.value=value;void load()} function openCreate(){editing.value=null;Object.assign(form,{name:'',org_type:'INTERNAL',is_active:true});modal.value=true} function openEdit(item:Organization){editing.value=item;Object.assign(form,{name:item.name,org_type:item.org_type,is_active:item.is_active});modal.value=true}
async function save(){saving.value=true;try{if(editing.value)await adminApi.updateOrganization(editing.value.id,{name:form.name,is_active:form.is_active});else await adminApi.createOrganization({name:form.name,org_type:form.org_type});modal.value=false;await Promise.all([load(),loadCatalogs(true)])}finally{saving.value=false}}
onMounted(load)
</script>
<template><section class="page arco-page"><header class="page-header"><div><p class="eyebrow">系统管理</p><h1>组织管理</h1><p class="muted">维护内部组织、客户与供应商信息</p></div><a-button type="primary" @click="openCreate"><template #icon><IconPlus/></template>新建组织</a-button></header><a-card class="arco-filter-card" :bordered="false"><a-form :model="{}" layout="inline" @submit.prevent="query"><a-form-item label="组织名称"><a-input v-model.trim="search" placeholder="输入关键字" allow-clear/></a-form-item><a-form-item><a-button type="primary" html-type="submit"><template #icon><IconSearch/></template>查询</a-button></a-form-item></a-form></a-card>
<a-card class="arco-table-card" :bordered="false"><a-table :data="items" :loading="loading" :pagination="false" row-key="id"><template #columns><a-table-column title="组织名称" data-index="name"/><a-table-column title="组织类型"><template #cell="{record}"><a-tag color="arcoblue">{{typeName[record.org_type as OrganizationType]}}</a-tag></template></a-table-column><a-table-column title="状态"><template #cell="{record}"><a-tag :color="record.is_active?'green':'gray'">{{record.is_active?'已启用':'已停用'}}</a-tag></template></a-table-column><a-table-column title="更新时间"><template #cell="{record}">{{new Date(record.updated_at).toLocaleString('zh-CN')}}</template></a-table-column><a-table-column title="操作"><template #cell="{record}"><a-button type="text" @click="openEdit(record)"><template #icon><IconEdit/></template>编辑</a-button></template></a-table-column></template><template #empty><a-empty description="暂无组织"/></template></a-table><div class="arco-pagination"><span>共 {{total}} 条，第 {{page}} / {{totalPages}} 页</span><a-pagination :current="page" :page-size="pageSize" :total="total" @change="changePage"/></div></a-card>
<a-modal v-model:visible="modal" :title="editing?'编辑组织':'新建组织'" :ok-loading="saving" ok-text="保存" cancel-text="取消" @ok="save"><a-form :model="form" layout="vertical"><a-form-item field="name" label="组织名称" required><a-input v-model.trim="form.name" :max-length="255"/></a-form-item><a-form-item field="org_type" label="组织类型" required><a-select v-model="form.org_type" :disabled="!!editing"><a-option value="INTERNAL">内部组织</a-option><a-option value="CUSTOMER">客户</a-option><a-option value="VENDOR">供应商</a-option></a-select><template v-if="editing" #extra>当前接口不支持修改组织类型</template></a-form-item><a-form-item v-if="editing" label="启用状态"><a-switch v-model="form.is_active" checked-text="启用" unchecked-text="停用"/></a-form-item></a-form></a-modal></section></template>
