<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { assetApi } from '../api/assets'
import { rememberOperator, savedOperator } from '../api/inventory'
import { objectApi } from '../api/objects'
import type { ObjectType, PurchaseItem, PurchaseRequest } from '../types'

const requests = ref<PurchaseRequest[]>([]); const types = ref<ObjectType[]>([]); const loading = ref(false); const submitting = ref(false); const operatorId = ref(savedOperator())
const form = ref({ title: '', preferred_vendor: '', estimated_cost: undefined as number | undefined, justification: '' })
const items = ref<PurchaseItem[]>([{ object_type_id: '', quantity: 1, model: '', unit_budget: null, vendor: '' }])
const typeMap = computed(() => Object.fromEntries(types.value.map((item) => [item.id, item.display_name || item.name])))
const statusName: Record<string, string> = { DRAFT: '草稿', PENDING: '待审批', APPROVED: '已批准', REJECTED: '已驳回', CANCELLED: '已取消' }
function addItem() { items.value.push({ object_type_id: '', quantity: 1, model: '', unit_budget: null, vendor: '' }) }
function removeItem(index: number) { if (items.value.length > 1) items.value.splice(index, 1) }
async function load() { loading.value = true; try { requests.value = (await assetApi.purchases()).data.items } finally { loading.value = false } }
async function create() { if (!operatorId.value || !form.value.title || items.value.some((item) => !item.object_type_id || item.quantity < 1)) return; submitting.value = true; try { rememberOperator(operatorId.value); await assetApi.createPurchase({ ...form.value, requester_id: operatorId.value, currency: 'CNY', items: items.value.map((item) => ({ ...item, model: item.model || null, vendor: item.vendor || form.value.preferred_vendor || null, unit_budget: item.unit_budget || null })) }); form.value = { title: '', preferred_vendor: '', estimated_cost: undefined, justification: '' }; items.value = [{ object_type_id: '', quantity: 1, model: '', unit_budget: null, vendor: '' }]; await load() } finally { submitting.value = false } }
async function approve(item: PurchaseRequest) { if (!operatorId.value) return; rememberOperator(operatorId.value); await assetApi.approvePurchase(item.id, operatorId.value); await load() }
async function reject(item: PurchaseRequest) { if (!operatorId.value) return; const reason = window.prompt('请输入驳回原因'); if (!reason) return; rememberOperator(operatorId.value); await assetApi.rejectPurchase(item.id, operatorId.value, reason); await load() }
onMounted(async () => { types.value = (await objectApi.types()).data.items; await load() })
</script>

<template><section class="page"><header class="page-header"><div><p class="eyebrow">PROCUREMENT</p><h1>采购申请</h1><p class="muted">按基础设施对象类型提交采购清单并完成审批</p></div></header>
  <form class="card purchase-form" @submit.prevent="create"><div class="section-title"><h3>新建采购申请</h3></div><div class="form-grid purchase-fields"><label><span>申请标题</span><input v-model.trim="form.title" required placeholder="例如：采购 10 台 GB300 服务器" /></label><label><span>首选供应商</span><input v-model.trim="form.preferred_vendor" /></label><label><span>预算总额（CNY）</span><input v-model.number="form.estimated_cost" type="number" min="0" /></label><label><span>操作用户 ID</span><input v-model.trim="operatorId" required placeholder="申请人与审批人的用户 UUID" /></label></div><label class="wide-field"><span>申请说明</span><textarea v-model.trim="form.justification" rows="2"></textarea></label>
    <div class="items-heading"><strong>采购明细</strong><button class="link" type="button" @click="addItem">+ 添加明细</button></div><div class="purchase-items"><div v-for="(item, index) in items" :key="index" class="purchase-item"><label><span>对象类型</span><select v-model="item.object_type_id" required><option value="">请选择</option><option v-for="type in types" :key="type.id" :value="type.id">{{ type.display_name || type.name }}</option></select></label><label><span>型号</span><input v-model.trim="item.model" /></label><label><span>数量</span><input v-model.number="item.quantity" type="number" min="1" required /></label><label><span>单价预算</span><input v-model.number="item.unit_budget" type="number" min="0" /></label><button class="link danger item-remove" type="button" :disabled="items.length === 1" @click="removeItem(index)">移除</button></div></div><div class="form-actions"><button class="button primary" :disabled="submitting || !operatorId" type="submit">{{ submitting ? '提交中…' : '提交申请' }}</button></div></form>
  <section class="card table-card purchase-list"><div class="section-title"><h3>申请记录</h3><span class="muted">共 {{ requests.length }} 条</span></div><div v-if="loading" class="empty">正在加载…</div><div v-else-if="!requests.length" class="empty">暂无采购申请</div><div v-else class="table-scroll"><table><thead><tr><th>申请编号</th><th>标题</th><th>设备清单</th><th>供应商</th><th>预算</th><th>状态</th><th>创建时间</th><th>操作</th></tr></thead><tbody><tr v-for="item in requests" :key="item.id"><td class="name-cell">{{ item.request_number }}</td><td>{{ item.title }}</td><td>{{ item.items.map((part) => `${typeMap[part.object_type_id] || '未知类型'} × ${part.quantity}`).join('；') }}</td><td>{{ item.preferred_vendor || '—' }}</td><td>{{ item.estimated_cost == null ? '—' : `${item.currency || 'CNY'} ${item.estimated_cost}` }}</td><td><span class="status" :class="item.status.toLowerCase()">{{ statusName[item.status] || item.status }}</span></td><td>{{ new Date(item.created_at).toLocaleString('zh-CN') }}</td><td class="actions"><template v-if="item.status === 'PENDING'"><button class="link" :disabled="!operatorId" @click="approve(item)">批准</button><button class="link danger" :disabled="!operatorId" @click="reject(item)">驳回</button></template><span v-else>—</span></td></tr></tbody></table></div></section>
</section></template>
