<script setup lang="ts">
import { computed,onMounted,reactive,ref } from 'vue'
import { Message, Modal } from '@arco-design/web-vue'
import { IconEdit,IconPlus,IconSearch } from '@arco-design/web-vue/es/icon'
import { adminApi } from '../api/admin'
import { loadCatalogs,loadUsers,useCatalog } from '../stores/catalog'
import type { User } from '../types'
const {state}=useCatalog(),items=ref<User[]>([]),total=ref(0),page=ref(1),search=ref(''),loading=ref(false),saving=ref(false),modal=ref(false),editing=ref<User|null>(null),pageSize=20,totalPages=computed(()=>Math.max(1,Math.ceil(total.value/pageSize)))
const form=reactive({username:'',full_name:'',email:'',organization_id:''})
async function load(){loading.value=true;try{const {data}=await adminApi.users({search:search.value||undefined,page:page.value,page_size:pageSize});items.value=data.items;total.value=data.total}finally{loading.value=false}}
function query(){page.value=1;void load()} function reset(){search.value='';query()} function changePage(value:number){page.value=value;void load()}
function openCreate(){editing.value=null;Object.assign(form,{username:'',full_name:'',email:'',organization_id:state.organizations.find(item=>item.is_active)?.id||''});modal.value=true}
function openEdit(item:User){editing.value=item;Object.assign(form,{username:item.username,full_name:item.full_name||'',email:item.email,organization_id:item.organization_id});modal.value=true}
async function save(){saving.value=true;try{if(editing.value)await adminApi.updateUser(editing.value.id,{full_name:form.full_name||null,email:form.email,organization_id:form.organization_id});else await adminApi.createUser({...form,full_name:form.full_name||null});modal.value=false;await Promise.all([load(),loadUsers(true)]);Message.success(editing.value?'用户更新成功':'用户创建成功')}finally{saving.value=false}}
function toggle(item:User,value:boolean){Modal.confirm({title:value?'启用用户':'停用用户',content:`确认${value?'启用':'停用'}用户“${item.username}”吗？`,okText:'确认',cancelText:'取消',onOk:async()=>{await adminApi.updateUser(item.id,{is_active:value});await Promise.all([load(),loadUsers(true)])}})}
onMounted(async()=>{await loadCatalogs();await load()})
</script>
<template><section class="page arco-page"><header class="page-header"><div><p class="eyebrow">系统管理</p><h1>用户管理</h1><p class="muted">维护平台用户、所属组织与启用状态</p></div><a-button type="primary" @click="openCreate"><template #icon><IconPlus/></template>新建用户</a-button></header><a-card class="arco-filter-card" :bordered="false"><a-form :model="{}" layout="inline" @submit.prevent="query"><a-form-item label="用户名或姓名"><a-input v-model.trim="search" placeholder="输入关键字" allow-clear/></a-form-item><a-form-item><a-button type="primary" html-type="submit"><template #icon><IconSearch/></template>查询</a-button></a-form-item></a-form></a-card>
<a-card class="arco-table-card" :bordered="false"><a-table :data="items" :loading="loading" :pagination="false" row-key="id"><template #columns><a-table-column title="用户名" data-index="username"/><a-table-column title="姓名"><template #cell="{record}">{{record.full_name||'—'}}</template></a-table-column><a-table-column title="邮箱" data-index="email"/><a-table-column title="所属组织"><template #cell="{record}">{{record.organization_name||'—'}}</template></a-table-column><a-table-column title="状态"><template #cell="{record}"><a-tag :color="record.is_active?'green':'gray'">{{record.is_active?'已启用':'已停用'}}</a-tag></template></a-table-column><a-table-column title="操作"><template #cell="{record}"><a-space><a-button type="text" @click="openEdit(record)"><template #icon><IconEdit/></template>编辑</a-button><a-switch :model-value="record.is_active" checked-text="启用" unchecked-text="停用" @change="value=>toggle(record,Boolean(value))"/></a-space></template></a-table-column></template><template #empty><a-empty description="暂无用户"/></template></a-table><div class="arco-pagination"><span>共 {{total}} 条，第 {{page}} / {{totalPages}} 页</span><a-pagination :current="page" :page-size="pageSize" :total="total" @change="changePage"/></div></a-card>
<a-modal v-model:visible="modal" :title="editing?'编辑用户':'新建用户'" :ok-loading="saving" ok-text="保存" cancel-text="取消" @ok="save"><a-form :model="form" layout="vertical"><a-form-item field="username" label="用户名" required><a-input v-model.trim="form.username" :disabled="!!editing" :max-length="100"/></a-form-item><a-form-item label="姓名"><a-input v-model.trim="form.full_name" :max-length="255"/></a-form-item><a-form-item field="email" label="邮箱" required><a-input v-model.trim="form.email" :max-length="255"/></a-form-item><a-form-item field="organization_id" label="所属组织" required><a-select v-model="form.organization_id" placeholder="请选择组织"><a-option v-for="org in state.organizations.filter(item=>item.is_active)" :key="org.id" :value="org.id">{{org.name}}</a-option></a-select></a-form-item></a-form></a-modal></section></template>
