<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { useRouter } from 'vue-router'
import { IconArrowLeft } from '@arco-design/web-vue/es/icon'
import { objectApi } from '../api/objects'
import { operationsApi } from '../api/operations'
import type { InfrastructureObject, WorkOrderPriority, WorkOrderType } from '../types'
const router = useRouter(), objects = ref<InfrastructureObject[]>([]), saving = ref(false)
const form = reactive({ object_id: '', title: '', type: 'FAULT' as WorkOrderType, priority: 'MEDIUM' as WorkOrderPriority, description: '' })
async function submit() { if (!form.object_id || !form.title.trim()) return; saving.value = true; try { const { data } = await operationsApi.create({ ...form, title: form.title.trim(), description: form.description.trim() || null }); await router.push(`/work-orders/${data.id}`) } finally { saving.value = false } }
onMounted(async () => { objects.value = (await objectApi.list({ page: 1, page_size: 100 })).data.items })
</script>
<template><section class="page narrow arco-page"><header class="page-header"><div><a-link class="arco-back-link" @click="router.push('/work-orders')"><IconArrowLeft /> 返回工单列表</a-link><h1>新建工单</h1><p class="muted">选择基础设施对象并填写运维任务信息</p></div></header><a-card class="arco-form-card" :bordered="false" title="工单信息"><a-form :model="form" layout="vertical" @submit.prevent="submit"><div class="modal-form-grid"><a-form-item label="关联设备" required><a-select v-model="form.object_id" placeholder="请选择基础设施对象" allow-search><a-option v-for="item in objects" :key="item.id" :value="item.id">{{ item.name }}（{{ item.serial_number || item.model || '无序列号' }}）</a-option></a-select></a-form-item><a-form-item label="标题" required><a-input v-model="form.title" :max-length="255" show-word-limit placeholder="例如：GPU 温度过高" /></a-form-item><a-form-item label="工单类型" required><a-select v-model="form.type"><a-option value="FAULT">故障</a-option><a-option value="REPAIR">维修</a-option><a-option value="INSPECTION">巡检</a-option><a-option value="CHANGE">变更</a-option></a-select></a-form-item><a-form-item label="优先级" required><a-select v-model="form.priority"><a-option value="CRITICAL">紧急</a-option><a-option value="HIGH">高</a-option><a-option value="MEDIUM">中</a-option><a-option value="LOW">低</a-option></a-select></a-form-item></div><a-form-item label="问题描述"><a-textarea v-model="form.description" placeholder="描述发现的问题、现象及影响范围" :auto-size="{ minRows: 6, maxRows: 10 }" /></a-form-item><div class="arco-form-actions"><a-button @click="router.push('/work-orders')">取消</a-button><a-button type="primary" html-type="submit" :loading="saving" :disabled="!form.object_id || !form.title.trim()">提交工单</a-button></div></a-form></a-card></section></template>
