<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { useRoute } from 'vue-router'
import { DEMO_USER_ID } from '../api/client'; import { objectApi } from '../api/objects'; import { operationsApi } from '../api/operations'
import type { InfrastructureObject, WorkOrderDetail } from '../types'
const route=useRoute(); const id=route.params.id as string; const item=ref<WorkOrderDetail|null>(null); const objects=ref<InfrastructureObject[]>([]); const busy=ref(false); const modal=ref<'assign'|'repair'|'replacement'|null>(null)
const assignForm=reactive({assigned_to:DEMO_USER_ID}); const repairForm=reactive({repair_type:'ADJUSTMENT',description:'',repair_result:'SUCCESS',started_at:'',completed_at:'',verification_notes:''}); const replacementForm=reactive({repair_record_id:'',old_object_id:'',new_object_id:'',replacement_reason:'FAILURE',old_object_disposition:'RMA',replaced_at:'',notes:''})
const objectMap=computed(()=>Object.fromEntries(objects.value.map(value=>[value.id,value.name]))); const currentObject=computed(()=>item.value ? objectMap.value[item.value.related_object_id]||item.value.related_object_id : '—')
const statusName:Record<string,string>={CREATED:'已创建',ASSIGNED:'已分配',PROCESSING:'处理中',WAITING:'等待中',SUSPENDED:'已暂停',RESOLVED:'已解决',CLOSED:'已关闭',CANCELLED:'已取消',REOPENED:'已重开'}; const typeName:Record<string,string>={FAULT:'故障',REPAIR:'维修',INSPECTION:'巡检',CHANGE:'变更'}; const priorityName:Record<string,string>={CRITICAL:'紧急',HIGH:'高',MEDIUM:'中',LOW:'低'}; const repairTypeName:Record<string,string>={REPLACEMENT:'部件更换',UPGRADE:'升级',ADJUSTMENT:'调整',CLEANING:'清洁'}; const resultName:Record<string,string>={SUCCESS:'成功',FAILED:'失败',PARTIAL:'部分完成'}; const reasonName:Record<string,string>={FAILURE:'故障',UPGRADE:'升级',PREVENTIVE:'预防性更换'}
function format(value:string|null|undefined){return value?new Date(value).toLocaleString('zh-CN'):'—'}; function iso(value:string){return value?new Date(value).toISOString():undefined}
async function load(){item.value=(await operationsApi.get(id)).data}
async function action(kind:'start'|'resolve'|'close'){busy.value=true;try{await operationsApi[kind](id);await load()}finally{busy.value=false}}
async function assign(){busy.value=true;try{await operationsApi.assign(id,assignForm.assigned_to);modal.value=null;await load()}finally{busy.value=false}}
async function repair(){busy.value=true;try{await operationsApi.repair(id,{object_id:item.value?.related_object_id,repair_type:repairForm.repair_type,description:repairForm.description,repair_result:repairForm.repair_result,started_at:iso(repairForm.started_at),completed_at:iso(repairForm.completed_at),verification_notes:repairForm.verification_notes||null});modal.value=null;repairForm.description='';await load()}finally{busy.value=false}}
async function replacement(){busy.value=true;try{await operationsApi.replacement(id,{...replacementForm,repair_record_id:replacementForm.repair_record_id||undefined,replaced_at:iso(replacementForm.replaced_at),notes:replacementForm.notes||null});modal.value=null;await load()}finally{busy.value=false}}
function eventTitle(event:WorkOrderDetail['timeline'][number]){if(event.type==='STATUS')return `状态变更：${statusName[event.status||'']||event.status}`;if(event.type==='REPAIR'){const record=item.value?.repairs.find(value=>value.id===event.record_id);return `维修记录：${record?.description||event.record_id}`}const record=item.value?.replacements.find(value=>value.id===event.record_id);return `部件更换：${record?`${objectMap.value[record.old_object_id]||record.old_object_id} → ${objectMap.value[record.new_object_id]||record.new_object_id}`:event.record_id}`}
onMounted(async()=>{const [objectResult]=await Promise.all([objectApi.list({page:1,page_size:100}),load()]);objects.value=objectResult.data.items})
</script>
<template><section v-if="item" class="page"><header class="page-header"><div><RouterLink class="back" to="/work-orders">← 返回工单列表</RouterLink><div class="title-row"><h1>{{item.work_order_number}}</h1><span class="status" :class="item.status.toLowerCase()">{{statusName[item.status]}}</span></div><p class="muted">{{item.title}}</p></div><div class="detail-actions"><button v-if="item.status==='CREATED'" class="button primary" @click="modal='assign'">分配工单</button><template v-if="item.status==='ASSIGNED'"><button class="button primary" :disabled="busy" @click="action('start')">开始处理</button><button class="button" @click="modal='repair'">记录维修</button></template><template v-if="item.status==='PROCESSING'"><button class="button" @click="modal='repair'">记录维修</button><button class="button" :disabled="!item.repairs.length" @click="modal='replacement'">部件更换</button><button class="button primary" :disabled="busy" @click="action('resolve')">解决工单</button></template><button v-if="item.status==='RESOLVED'" class="button primary" :disabled="busy" @click="action('close')">关闭工单</button></div></header>
<div class="operations-grid"><div><article class="card detail-section"><div class="section-title"><h3>基本信息</h3></div><dl class="description-grid single"><div><dt>工单类型</dt><dd>{{typeName[item.type]}}</dd></div><div><dt>优先级</dt><dd>{{priorityName[item.priority]}}</dd></div><div><dt>关联设备</dt><dd><RouterLink :to="`/objects/${item.related_object_id}`">{{currentObject}}</RouterLink></dd></div><div><dt>处理人</dt><dd class="id-cell">{{item.assigned_to||'未分配'}}</dd></div><div><dt>创建时间</dt><dd>{{format(item.created_at)}}</dd></div><div><dt>描述</dt><dd>{{item.description||'—'}}</dd></div></dl></article>
<article class="card detail-section"><div class="section-title"><h3>维修记录</h3><span class="muted">{{item.repairs.length}} 条</span></div><div v-if="!item.repairs.length" class="inline-empty">暂无维修记录</div><div v-else class="record-list"><div v-for="record in item.repairs" :key="record.id" class="record-row"><header><strong>{{repairTypeName[record.repair_type]||record.repair_type}}</strong><span class="status">{{resultName[record.repair_result]||record.repair_result}}</span></header><p>{{record.description}}</p><small>{{format(record.started_at)}} · 工程师 {{record.engineer_id}}</small><p v-if="record.verification_notes" class="muted">验证：{{record.verification_notes}}</p></div></div></article>
<article class="card detail-section"><div class="section-title"><h3>部件更换</h3><span class="muted">{{item.replacements.length}} 条</span></div><div v-if="!item.replacements.length" class="inline-empty">暂无部件更换记录</div><div v-else class="record-list"><div v-for="record in item.replacements" :key="record.id" class="record-row"><header><strong>{{objectMap[record.old_object_id]||record.old_object_id}} → {{objectMap[record.new_object_id]||record.new_object_id}}</strong><span>{{reasonName[record.replacement_reason]||record.replacement_reason}}</span></header><p>{{record.notes||'未填写备注'}}</p><small>{{format(record.replaced_at)}} · 工程师 {{record.engineer_id}}</small></div></div></article></div>
<article class="card timeline-card"><div class="section-title"><h3>处理时间线</h3></div><div class="timeline"><div v-for="(event,index) in item.timeline" :key="`${event.type}-${event.record_id||event.status}-${index}`" class="timeline-item"><i class="timeline-dot"></i><header><strong>{{eventTitle(event)}}</strong></header><p>{{format(event.at)}}</p><small class="id-cell">操作人 {{event.operator_id}}</small></div></div></article></div>
<div v-if="modal" class="modal-mask" @click.self="modal=null"><form v-if="modal==='assign'" class="modal card" @submit.prevent="assign"><header><div><p class="eyebrow">ASSIGN</p><h2>分配工单</h2></div><button class="modal-close" type="button" @click="modal=null">×</button></header><label><span>工程师用户 ID *</span><input v-model.trim="assignForm.assigned_to" required /></label><footer><button class="button" type="button" @click="modal=null">取消</button><button class="button primary" :disabled="busy">确认分配</button></footer></form>
<form v-else-if="modal==='repair'" class="modal card" @submit.prevent="repair"><header><div><p class="eyebrow">REPAIR</p><h2>记录维修</h2></div><button class="modal-close" type="button" @click="modal=null">×</button></header><div class="form-grid"><label><span>维修类型 *</span><select v-model="repairForm.repair_type"><option value="ADJUSTMENT">调整</option><option value="CLEANING">清洁</option><option value="UPGRADE">升级</option><option value="REPLACEMENT">部件更换</option></select></label><label><span>维修结果 *</span><select v-model="repairForm.repair_result"><option value="SUCCESS">成功</option><option value="PARTIAL">部分完成</option><option value="FAILED">失败</option></select></label><label><span>开始时间</span><input v-model="repairForm.started_at" type="datetime-local" /></label><label><span>完成时间</span><input v-model="repairForm.completed_at" type="datetime-local" /></label></div><label><span>维修内容 *</span><textarea v-model.trim="repairForm.description" required rows="4"></textarea></label><label><span>验证说明</span><textarea v-model="repairForm.verification_notes" rows="2"></textarea></label><footer><button class="button" type="button" @click="modal=null">取消</button><button class="button primary" :disabled="busy">保存记录</button></footer></form>
<form v-else class="modal card" @submit.prevent="replacement"><header><div><p class="eyebrow">REPLACEMENT</p><h2>记录部件更换</h2></div><button class="modal-close" type="button" @click="modal=null">×</button></header><div class="form-grid"><label><span>关联维修记录 *</span><select v-model="replacementForm.repair_record_id" required><option value="" disabled>请选择</option><option v-for="record in item.repairs" :key="record.id" :value="record.id">{{record.description}}</option></select></label><label><span>更换时间</span><input v-model="replacementForm.replaced_at" type="datetime-local" /></label><label><span>旧部件 *</span><select v-model="replacementForm.old_object_id" required><option value="" disabled>请选择对象</option><option v-for="value in objects" :key="value.id" :value="value.id">{{value.name}}</option></select></label><label><span>新部件 *</span><select v-model="replacementForm.new_object_id" required><option value="" disabled>请选择对象</option><option v-for="value in objects" :key="value.id" :value="value.id">{{value.name}}</option></select></label><label><span>更换原因 *</span><select v-model="replacementForm.replacement_reason"><option value="FAILURE">故障</option><option value="UPGRADE">升级</option><option value="PREVENTIVE">预防性更换</option></select></label><label><span>旧件处置 *</span><select v-model="replacementForm.old_object_disposition"><option value="RMA">返厂</option><option value="STOCK">入库</option><option value="RETIRED">退役</option><option value="SCRAPPED">报废</option></select></label></div><label><span>更换说明</span><textarea v-model="replacementForm.notes" rows="3"></textarea></label><footer><button class="button" type="button" @click="modal=null">取消</button><button class="button primary" :disabled="busy">保存更换</button></footer></form></div>
</section><section v-else class="page"><div class="empty">正在加载…</div></section></template>
