<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { IconArrowLeft, IconPlus } from '@arco-design/web-vue/es/icon'
import { objectApi } from '../api/objects'
import { operationsApi } from '../api/operations'
import { currentUser } from '../stores/auth'
import { loadUsers, useCatalog } from '../stores/catalog'
import type { InfrastructureObject, WorkOrderDetail } from '../types'
const route = useRoute(), router = useRouter(), id = route.params.id as string
const item = ref<WorkOrderDetail | null>(null), objects = ref<InfrastructureObject[]>([]), busy = ref(false), modal = ref<'assign' | 'repair' | 'replacement' | null>(null)
const { state, userMap } = useCatalog()
const assignForm = reactive({ assigned_to: currentUser.value?.id || '' })
const repairForm = reactive({ repair_type: 'ADJUSTMENT', description: '', repair_result: 'SUCCESS', started_at: '', completed_at: '', verification_notes: '' })
const replacementForm = reactive({ repair_record_id: '', old_object_id: '', new_object_id: '', replacement_reason: 'FAILURE', old_object_disposition: 'RMA', replaced_at: '', notes: '' })
const objectMap = computed(() => Object.fromEntries(objects.value.map(value => [value.id, value.name])))
const currentObject = computed(() => item.value ? objectMap.value[item.value.related_object_id] || item.value.related_object_id : '—')
const statusName: Record<string, string> = { CREATED: '已创建', ASSIGNED: '已分配', PROCESSING: '处理中', WAITING: '等待中', SUSPENDED: '已暂停', RESOLVED: '已解决', CLOSED: '已关闭', CANCELLED: '已取消', REOPENED: '已重开' }
const typeName: Record<string, string> = { FAULT: '故障', REPAIR: '维修', INSPECTION: '巡检', CHANGE: '变更' }
const priorityName: Record<string, string> = { CRITICAL: '紧急', HIGH: '高', MEDIUM: '中', LOW: '低' }
const repairTypeName: Record<string, string> = { REPLACEMENT: '部件更换', UPGRADE: '升级', ADJUSTMENT: '调整', CLEANING: '清洁' }
const resultName: Record<string, string> = { SUCCESS: '成功', FAILED: '失败', PARTIAL: '部分完成' }
const reasonName: Record<string, string> = { FAILURE: '故障', UPGRADE: '升级', PREVENTIVE: '预防性更换' }
const statusColor = (value: string) => ({ CREATED: 'blue', ASSIGNED: 'arcoblue', PROCESSING: 'orange', WAITING: 'gold', SUSPENDED: 'gray', RESOLVED: 'green', CLOSED: 'gray', CANCELLED: 'red', REOPENED: 'purple' }[value] || 'gray')
const priorityColor = (value: string) => ({ CRITICAL: 'red', HIGH: 'orangered', MEDIUM: 'orange', LOW: 'blue' }[value] || 'gray')
function format(value: string | null | undefined) { return value ? new Date(value).toLocaleString('zh-CN') : '—' }
function iso(value: string) { return value ? new Date(value).toISOString() : undefined }
async function load() { item.value = (await operationsApi.get(id)).data }
async function action(kind: 'start' | 'resolve' | 'close') { busy.value = true; try { await operationsApi[kind](id); await load() } finally { busy.value = false } }
async function assign() { busy.value = true; try { await operationsApi.assign(id, assignForm.assigned_to); modal.value = null; await load() } finally { busy.value = false } }
async function repair() { busy.value = true; try { await operationsApi.repair(id, { object_id: item.value?.related_object_id, repair_type: repairForm.repair_type, description: repairForm.description, repair_result: repairForm.repair_result, started_at: iso(repairForm.started_at), completed_at: iso(repairForm.completed_at), verification_notes: repairForm.verification_notes || null }); modal.value = null; repairForm.description = ''; await load() } finally { busy.value = false } }
async function replacement() { busy.value = true; try { await operationsApi.replacement(id, { ...replacementForm, repair_record_id: replacementForm.repair_record_id || undefined, replaced_at: iso(replacementForm.replaced_at), notes: replacementForm.notes || null }); modal.value = null; await load() } finally { busy.value = false } }
function eventTitle(event: WorkOrderDetail['timeline'][number]) { if (event.type === 'STATUS') return `状态变更：${statusName[event.status || ''] || event.status}`; if (event.type === 'REPAIR') return `维修记录：${item.value?.repairs.find(value => value.id === event.record_id)?.description || event.record_id}`; const record = item.value?.replacements.find(value => value.id === event.record_id); return `部件更换：${record ? `${objectMap.value[record.old_object_id] || record.old_object_id} → ${objectMap.value[record.new_object_id] || record.new_object_id}` : event.record_id}` }
onMounted(async () => { const [objectResult] = await Promise.all([objectApi.list({ page: 1, page_size: 100 }), load(), loadUsers()]); objects.value = objectResult.data.items })
</script>
<template><section v-if="item" class="page arco-page"><header class="page-header"><div><a-link class="arco-back-link" @click="router.push('/work-orders')"><IconArrowLeft /> 返回工单列表</a-link><div class="title-row"><h1>{{ item.work_order_number }}</h1><a-tag :color="statusColor(item.status)" bordered>{{ statusName[item.status] }}</a-tag></div><p class="muted">{{ item.title }}</p></div><a-space wrap><a-button v-if="item.status === 'CREATED'" type="primary" @click="modal = 'assign'">分配工单</a-button><template v-if="item.status === 'ASSIGNED'"><a-button type="primary" :loading="busy" @click="action('start')">开始处理</a-button><a-button status="warning" @click="modal = 'repair'">记录维修</a-button></template><template v-if="item.status === 'PROCESSING'"><a-button status="warning" @click="modal = 'repair'">记录维修</a-button><a-button :disabled="!item.repairs.length" @click="modal = 'replacement'">部件更换</a-button><a-button type="primary" :loading="busy" @click="action('resolve')">解决工单</a-button></template><a-button v-if="item.status === 'RESOLVED'" type="primary" :loading="busy" @click="action('close')">关闭工单</a-button></a-space></header>
<div class="arco-operations-grid"><div><a-card class="arco-detail-card" :bordered="false" title="基本信息"><a-descriptions :column="2" bordered size="large"><a-descriptions-item label="工单类型">{{ typeName[item.type] }}</a-descriptions-item><a-descriptions-item label="优先级"><a-tag :color="priorityColor(item.priority)">{{ priorityName[item.priority] }}</a-tag></a-descriptions-item><a-descriptions-item label="关联设备"><a-link @click="router.push(`/objects/${item.related_object_id}`)">{{ currentObject }}</a-link></a-descriptions-item><a-descriptions-item label="处理人">{{ userMap[item.assigned_to || ''] || '未分配' }}</a-descriptions-item><a-descriptions-item label="创建时间">{{ format(item.created_at) }}</a-descriptions-item><a-descriptions-item label="更新时间">{{ format(item.updated_at) }}</a-descriptions-item><a-descriptions-item label="问题描述" :span="2">{{ item.description || '—' }}</a-descriptions-item></a-descriptions></a-card>
<a-card class="arco-record-card" :bordered="false"><template #title>维修记录</template><template #extra><a-button v-if="['ASSIGNED', 'PROCESSING'].includes(item.status)" type="text" @click="modal = 'repair'"><template #icon><IconPlus /></template>添加记录</a-button></template><a-table :data="item.repairs" :pagination="false" row-key="id"><template #columns><a-table-column title="维修类型" :width="110"><template #cell="{ record }">{{ repairTypeName[record.repair_type] || record.repair_type }}</template></a-table-column><a-table-column title="维修内容" data-index="description" ellipsis tooltip /><a-table-column title="结果" :width="100"><template #cell="{ record }"><a-tag :color="record.repair_result === 'SUCCESS' ? 'green' : record.repair_result === 'FAILED' ? 'red' : 'orange'">{{ resultName[record.repair_result] || record.repair_result }}</a-tag></template></a-table-column><a-table-column title="工程师" :width="120"><template #cell="{ record }">{{ userMap[record.engineer_id] || record.engineer_id }}</template></a-table-column><a-table-column title="开始时间" :width="180"><template #cell="{ record }">{{ format(record.started_at) }}</template></a-table-column></template><template #empty><a-empty description="暂无维修记录" /></template></a-table></a-card>
<a-card class="arco-record-card" :bordered="false"><template #title>部件更换记录</template><template #extra><a-button v-if="item.status === 'PROCESSING'" type="text" :disabled="!item.repairs.length" @click="modal = 'replacement'"><template #icon><IconPlus /></template>添加记录</a-button></template><a-table :data="item.replacements" :pagination="false" row-key="id"><template #columns><a-table-column title="旧部件" :width="160"><template #cell="{ record }">{{ objectMap[record.old_object_id] || record.old_object_id }}</template></a-table-column><a-table-column title="新部件" :width="160"><template #cell="{ record }">{{ objectMap[record.new_object_id] || record.new_object_id }}</template></a-table-column><a-table-column title="原因" :width="110"><template #cell="{ record }">{{ reasonName[record.replacement_reason] || record.replacement_reason }}</template></a-table-column><a-table-column title="更换说明" data-index="notes" ellipsis tooltip /><a-table-column title="更换时间" :width="180"><template #cell="{ record }">{{ format(record.replaced_at) }}</template></a-table-column></template><template #empty><a-empty description="暂无部件更换记录" /></template></a-table></a-card></div>
<a-card class="arco-timeline-card" :bordered="false" title="处理时间线"><a-empty v-if="!item.timeline.length" description="暂无处理记录" /><a-timeline v-else><a-timeline-item v-for="(event, index) in item.timeline" :key="`${event.type}-${event.record_id || event.status}-${index}`" :label="format(event.at)" :dot-color="event.type === 'STATUS' ? '#165dff' : event.type === 'REPAIR' ? '#ff7d00' : '#00b42a'"><strong>{{ eventTitle(event) }}</strong><p class="timeline-operator">操作人：{{ userMap[event.operator_id] || event.operator_id }}</p></a-timeline-item></a-timeline></a-card></div>
<a-modal :visible="modal === 'assign'" title="分配工单" ok-text="确认分配" cancel-text="取消" :ok-loading="busy" :ok-button-props="{ disabled: !assignForm.assigned_to }" @ok="assign" @cancel="modal = null"><a-form :model="assignForm" layout="vertical"><a-form-item label="处理人" required><a-select v-model="assignForm.assigned_to" placeholder="请选择用户"><a-option v-for="user in state.users.filter(value => value.is_active)" :key="user.id" :value="user.id">{{ user.full_name || user.username }}</a-option></a-select></a-form-item></a-form></a-modal>
<a-modal :visible="modal === 'repair'" title="记录维修" ok-text="保存记录" cancel-text="取消" :ok-loading="busy" :ok-button-props="{ disabled: !repairForm.description.trim() }" width="720px" @ok="repair" @cancel="modal = null"><a-form :model="repairForm" layout="vertical"><div class="modal-form-grid"><a-form-item label="维修类型" required><a-select v-model="repairForm.repair_type"><a-option value="ADJUSTMENT">调整</a-option><a-option value="CLEANING">清洁</a-option><a-option value="UPGRADE">升级</a-option><a-option value="REPLACEMENT">部件更换</a-option></a-select></a-form-item><a-form-item label="维修结果" required><a-select v-model="repairForm.repair_result"><a-option value="SUCCESS">成功</a-option><a-option value="PARTIAL">部分完成</a-option><a-option value="FAILED">失败</a-option></a-select></a-form-item><a-form-item label="开始时间"><a-date-picker v-model="repairForm.started_at" show-time value-format="YYYY-MM-DDTHH:mm:ss" /></a-form-item><a-form-item label="完成时间"><a-date-picker v-model="repairForm.completed_at" show-time value-format="YYYY-MM-DDTHH:mm:ss" /></a-form-item></div><a-form-item label="维修内容" required><a-textarea v-model="repairForm.description" :auto-size="{ minRows: 3, maxRows: 6 }" /></a-form-item><a-form-item label="验证说明"><a-textarea v-model="repairForm.verification_notes" :auto-size="{ minRows: 2, maxRows: 4 }" /></a-form-item></a-form></a-modal>
<a-modal :visible="modal === 'replacement'" title="记录部件更换" ok-text="保存更换" cancel-text="取消" :ok-loading="busy" :ok-button-props="{ disabled: !replacementForm.repair_record_id || !replacementForm.old_object_id || !replacementForm.new_object_id }" width="760px" @ok="replacement" @cancel="modal = null"><a-form :model="replacementForm" layout="vertical"><div class="modal-form-grid"><a-form-item label="关联维修记录" required><a-select v-model="replacementForm.repair_record_id" placeholder="请选择"><a-option v-for="record in item.repairs" :key="record.id" :value="record.id">{{ record.description }}</a-option></a-select></a-form-item><a-form-item label="更换时间"><a-date-picker v-model="replacementForm.replaced_at" show-time value-format="YYYY-MM-DDTHH:mm:ss" /></a-form-item><a-form-item label="旧部件" required><a-select v-model="replacementForm.old_object_id" placeholder="请选择对象" allow-search><a-option v-for="value in objects" :key="value.id" :value="value.id">{{ value.name }}</a-option></a-select></a-form-item><a-form-item label="新部件" required><a-select v-model="replacementForm.new_object_id" placeholder="请选择对象" allow-search><a-option v-for="value in objects" :key="value.id" :value="value.id">{{ value.name }}</a-option></a-select></a-form-item><a-form-item label="更换原因" required><a-select v-model="replacementForm.replacement_reason"><a-option value="FAILURE">故障</a-option><a-option value="UPGRADE">升级</a-option><a-option value="PREVENTIVE">预防性更换</a-option></a-select></a-form-item><a-form-item label="旧件处置" required><a-select v-model="replacementForm.old_object_disposition"><a-option value="RMA">返厂</a-option><a-option value="STOCK">入库</a-option><a-option value="RETIRED">退役</a-option><a-option value="SCRAPPED">报废</a-option></a-select></a-form-item></div><a-form-item label="更换说明"><a-textarea v-model="replacementForm.notes" :auto-size="{ minRows: 3, maxRows: 5 }" /></a-form-item></a-form></a-modal>
</section><section v-else class="page arco-page"><a-spin loading tip="正在加载工单详情…" class="page-loading" /></section></template>
