<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { useRouter } from 'vue-router'
import { IconPlus, IconSearch } from '@arco-design/web-vue/es/icon'
import { objectApi } from '../api/objects'
import { operationsApi } from '../api/operations'
import { loadUsers, useCatalog } from '../stores/catalog'
import type { InfrastructureObject, WorkOrder } from '../types'
const router = useRouter()
const items = ref<WorkOrder[]>([]), objects = ref<InfrastructureObject[]>([]), loading = ref(false)
const total = ref(0), page = ref(1), status = ref(''), type = ref(''), keyword = ref(''), pageSize = 20
const { userMap } = useCatalog()
const objectMap = computed(() => Object.fromEntries(objects.value.map(item => [item.id, item.name])))
const visibleItems = computed(() => { const value = keyword.value.trim().toLowerCase(); return value ? items.value.filter(item => `${item.work_order_number} ${item.title} ${objectMap.value[item.related_object_id] || ''}`.toLowerCase().includes(value)) : items.value })
const statusName: Record<string, string> = { CREATED: '已创建', ASSIGNED: '已分配', PROCESSING: '处理中', WAITING: '等待中', SUSPENDED: '已暂停', RESOLVED: '已解决', CLOSED: '已关闭', CANCELLED: '已取消', REOPENED: '已重开' }
const typeName: Record<string, string> = { FAULT: '故障', REPAIR: '维修', INSPECTION: '巡检', CHANGE: '变更' }
const priorityName: Record<string, string> = { CRITICAL: '紧急', HIGH: '高', MEDIUM: '中', LOW: '低' }
const statusColor = (value: string) => ({ CREATED: 'blue', ASSIGNED: 'arcoblue', PROCESSING: 'orange', WAITING: 'gold', SUSPENDED: 'gray', RESOLVED: 'green', CLOSED: 'gray', CANCELLED: 'red', REOPENED: 'purple' }[value] || 'gray')
const priorityColor = (value: string) => ({ CRITICAL: 'red', HIGH: 'orangered', MEDIUM: 'orange', LOW: 'blue' }[value] || 'gray')
function format(value: string) { return new Date(value).toLocaleString('zh-CN') }
async function load() { loading.value = true; try { const { data } = await operationsApi.list({ status: status.value || undefined, type: type.value || undefined, page: page.value, page_size: pageSize }); items.value = data.items; total.value = data.total } finally { loading.value = false } }
function filter() { page.value = 1; void load() }
function reset() { status.value = ''; type.value = ''; keyword.value = ''; filter() }
onMounted(async () => { const [objectResult] = await Promise.all([objectApi.list({ page: 1, page_size: 100 }), load(), loadUsers()]); objects.value = objectResult.data.items })
</script>
<template><section class="page arco-page"><header class="page-header"><div><p class="eyebrow">运维管理</p><h1>运维工单</h1><p class="muted">跟踪基础设施故障、维修与巡检处理过程</p></div><a-button type="primary" @click="router.push('/work-orders/new')"><template #icon><IconPlus /></template>新建工单</a-button></header>
<a-card class="arco-filter-card" :bordered="false"><a-form :model="{}" layout="inline" @submit.prevent="filter"><a-form-item label="工单状态"><a-select v-model="status" placeholder="全部状态" allow-clear><a-option value="">全部状态</a-option><a-option v-for="(name, value) in statusName" :key="value" :value="value">{{ name }}</a-option></a-select></a-form-item><a-form-item label="工单类型"><a-select v-model="type" placeholder="全部类型" allow-clear><a-option value="">全部类型</a-option><a-option v-for="(name, value) in typeName" :key="value" :value="value">{{ name }}</a-option></a-select></a-form-item><a-form-item label="关键词"><a-input v-model="keyword" placeholder="工单号、标题或设备" allow-clear><template #prefix><IconSearch /></template></a-input></a-form-item><a-form-item><a-space><a-button type="primary" html-type="submit">查询</a-button><a-button @click="reset">重置</a-button></a-space></a-form-item></a-form></a-card>
<a-card class="arco-table-card" :bordered="false"><a-table :data="visibleItems" :loading="loading" :pagination="false" row-key="id" :scroll="{ x: 1280 }" @row-click="(record) => router.push(`/work-orders/${(record as WorkOrder).id}`)"><template #columns><a-table-column title="工单号" data-index="work_order_number" :width="175"><template #cell="{ record }"><a-link class="object-name">{{ record.work_order_number }}</a-link></template></a-table-column><a-table-column title="标题" data-index="title" :width="220" ellipsis tooltip /><a-table-column title="类型" :width="90"><template #cell="{ record }">{{ typeName[record.type] }}</template></a-table-column><a-table-column title="状态" :width="105"><template #cell="{ record }"><a-tag :color="statusColor(record.status)" bordered>{{ statusName[record.status] }}</a-tag></template></a-table-column><a-table-column title="优先级" :width="90"><template #cell="{ record }"><a-tag :color="priorityColor(record.priority)" bordered>{{ priorityName[record.priority] }}</a-tag></template></a-table-column><a-table-column title="关联设备" :width="180"><template #cell="{ record }">{{ objectMap[record.related_object_id] || record.related_object_id }}</template></a-table-column><a-table-column title="创建时间" :width="180"><template #cell="{ record }">{{ format(record.created_at) }}</template></a-table-column><a-table-column title="处理人" :width="130"><template #cell="{ record }">{{ userMap[record.assigned_to || ''] || '未分配' }}</template></a-table-column><a-table-column title="操作" fixed="right" :width="80"><template #cell="{ record }"><a-button type="text" size="small" @click.stop="router.push(`/work-orders/${record.id}`)">详情</a-button></template></a-table-column></template><template #empty><a-empty class="atlas-empty-guide" description="暂无工单，可创建工单开始跟踪运维事项"><a-button type="primary" @click="router.push('/work-orders/new')">新建工单</a-button></a-empty></template></a-table><div class="arco-pagination"><span>共 {{ total }} 条</span><a-pagination :current="page" :page-size="pageSize" :total="total" :show-total="false" @change="(value) => { page = value; load() }" /></div></a-card></section></template>
